import com.sample.Drools.Message;
rule "1"
	when
		m:Message(message=="เชื้อรา" || message=="ที่เกิดจากเชื้อรา");
	then
		m.addResult("เมล็ดด่าง","โรค");
		m.addResult("ขอบใบแห้ง","โรค");
		m.addResult("กาบใบแห้ง","โรค");
		m.addResult("ใบจุดสีน้ำตาล","โรค");
		m.addResult("ถอดฝักดาบ","โรค");
		m.addResult("ใบขีดสีน้ำตาล","โรค");
		m.addResult("กล้าเน่าในกระบะเพาะ","โรค");
		m.addResult("ลำต้นเน่า","โรค");
end
rule "2"
	when
		m:Message(message=="ที่ปลูกในนาน้ำฝน" || message=="ปลูกในนาน้ำฝน" || message=="นาน้ำฝน");
	then
		m.addResult("ถอดฝักดาบ","โรค");
		m.addResult("ลำต้นเน่า","โรค");
		m.addResult("ไหม้","โรค");
		m.addResult("ใบจุดสีน้ำตาล","โรค");
		m.addResult("ใบขีดสีน้ำตาล","โรค");
		m.addResult("รากปม","โรค");
		m.addResult("ขอบใบแห้ง","โรค");
end
rule "3"
	when
		m:Message(message=="ที่ปลูกในนาชลประทาน" || message=="ปลูกในนาชลประทาน" || message=="นาชลประทาน");
	then
		m.addResult("ขอบใบแห้ง","โรค");
		m.addResult("กาบใบแห้ง","โรค");
		m.addResult("ลำต้นเน่า","โรค");
		m.addResult("เมล็ดด่าง","โรค");
		m.addResult("ใบจุดสีน้ำตาล","โรค");
		m.addResult("ใบขีดสีน้ำตาล","โรค");
		m.addResult("ใบวงสีน้ำตาล","โรค");
		m.addResult("กล้าเน่าในกระบะเพาะ","โรค");
end
rule "4"
	when
		m:Message(message=="มีความชื้นสูง" || message=="ชื้นมาก" || message=="ปลูกในที่ชื้น");
	then
		m.addResult("ขอบใบแห้ง","โรค");
end
rule "5"
	when
		m:Message(message=="มีเพลี้ยจักจั่นปีกลายหยัก" || message=="เกิดจากเพลี้ยจักจั่นปีกลายหยัก" || message=="ที่เกิดจากเพลี้ยจักจั่นปีกลายหยัก");
	then
		m.addResult("ใบสีส้ม","โรค");
		m.addResult("หูด","โรค");
end
rule "6"
	when
		m:Message(message=="มีพืชอาศัย" || message=="เกิดจากพืชอาศัย" || message=="ที่เกิดจากพืชอาศัย");
	then
		m.addResult("ใบวงสีน้ำตาล","โรค");
		m.addResult("ถอดฝักดาบ","โรค");
		m.addResult("รากปม","โรค");
		m.addResult("ใบสีส้ม","โรค");
end
rule "7"
	when
		m:Message(message=="มีลมพัด" || message=="เกิดจากลมพัด" || message=="ที่เกิดจากลมพัด");
	then
		m.addResult("ขอบใบแห้ง","โรค");
		m.addResult("ไหม้","โรค");
		m.addResult("ใบขีดสีน้ำตาล","โรค");
		m.addResult("เมล็ดด่าง","โรค");
		m.addResult("ใบจุดสีน้ำตาล","โรค");
end
rule "8"
	when
		m:Message(message=="ปลูกต้นข้าวหนาแน่น" || message=="เกิดจากปลูกต้นข้าวหนาเเน่น" || message=="ที่เกิดจากปลูกข้าวหนาเเน่น");
	then
		m.addResult("ไหม้","โรค");
end
rule "9"
	when
		m:Message(message=="เชียงราย" || message=="เชียงใหม่" || message=="น่าน" || message=="พะเยา" || message=="แพร่" || message=="แม่ฮ่องสอน" || message=="ลำปาง" || message=="ลำพูน" || message=="อุตรดิตถ์" || message=="ตาก" || message=="พิษณุโลก" || message=="สุโขทัย" || message=="เพชรบูรณ์" || message=="พิจิตร" || message=="กำเเพงเพชร" || message=="นครสวรรค์" || message=="อุทัยธานี");
	then
		m.addResult("ภาคเหนือ","ภาค");
end
rule "10"
	when
		m:Message(message=="เชียงราย" || message=="เชียงใหม่" || message=="น่าน" || message=="พะเยา" || message=="แพร่" || message=="แม่ฮ่องสอน" || message=="ลำปาง" || message=="ลำพูน" || message=="อุตรดิตถ์");
	then
		m.addResult("ภาคเหนือตอนบน","ภาค");
end
rule "11"
	when
		m:Message(message=="ตาก" || message=="พิษณุโลก" || message=="สุโขทัย" || message=="เพชรบูรณ์" || message=="พิจิตร" || message=="กำเเพงเพชร" || message=="นครสวรรค์" || message=="อุทัยธานี");
	then
		m.addResult("ภาคเหนือตอนล่าง","ภาค");
end
rule "12"
	when
		m:Message(message=="ทนแล้ง" || message=="ที่ทนเเล้ง");
	then
		m.addResult("ขาวดอกมะลิ105","ข้าว");
		m.addResult("กข6","ข้าว");
end
rule "13"
	when
		m:Message(message=="ทนดินเปรี้ยว" || message=="ที่ทนดินเปรี้ยว");
	then
		m.addResult("ขาวดอกมะลิ","ข้าว");
end
rule "14"
	when
		m:Message(message=="ทนดินเค็ม" || message=="ที่ทนดินเค็ม");
	then
		m.addResult("ขาวดอกมะลิ","ข้าว");
		m.addResult("เหนียวสันป่าตอง","ข้าว");
end
rule "15"
	when
		m:Message(message=="ต้านทานใบจุดสีน้ำตาล" || message=="ที่ต้านทานใบจุดสีน้ำตาล" || message=="ที่ต้านใบจุดสีน้ำตาล");
	then
		m.addResult("กข6","ข้าว");
		m.addResult("เหนียวสันป่าตอง","ข้าว");
end
rule "16"
	when
		m:Message(message=="ต้านทานโรคไหม้" || message=="ที่ต้านทานโรคไหม้" || message=="ที่ต้านโรคไหม้");
	then
		m.addResult("เหนียวสันป่าตอง","ข้าว");
		m.addResult("สันป่าตอง","ข้าว");
		m.addResult("ชัยนาถ1","ข้าว");
		m.addResult("สุพรรณบุรี1","ข้าว");
		m.addResult("พิษณุโลก2","ข้าว");
		m.addResult("ปราจีนบุรี1","ข้าว");
end
rule "17"
	when
		m:Message(message=="ต้านทานขอบใบแห้ง" || message=="ที่ต้านทานขอบใบแห้ง" || message=="ที่ต้านขอบใบแห้ง");
	then
		m.addResult("สันป่าตอง","ข้าว");
		m.addResult("สุพรรณบุรี1","ข้าว");
		m.addResult("พิษณุโลก2","ข้าว");
end
rule "18"
	when
		m:Message(message=="ต้านทานใบส้ม" || message=="ที่ต้านทานใบส้ม" || message=="ที่ต้านใบส้ม");
	then
		m.addResult("สุพรรณบุรี1","ข้าว");
end
rule "19"
	when
		m:Message(message=="ต้านทานใบหงิก" || message=="ที่ต้านทานใบหงิก" || message=="ที่ต้านใบหงิก");
	then
		m.addResult("ชัยนาถ1","ข้าว");
		m.addResult("สุพรรณบุรี1","ข้าว");
end
rule "20"
	when
		m:Message(message=="ต้านทานเพลี้ยกระโดดสีน้ำตาล" || message=="ที่ต้านทานเพลี้ยกระโดดสีน้ำตาล" || message=="ที่ต้านเพลี้ยกระโดดสีน้ำตาล");
	then
		m.addResult("ชัยนาถ1","ข้าว");
		m.addResult("สุพรรณบุรี1","ข้าว");
		m.addResult("พิษณุโลก2","ข้าว");
end
rule "21"
	when
		m:Message(message=="ต้านทานเพลี้ยกระโดดหลังขาว" || message=="ที่ต้านทานเพลี้ยกระโดดหลังขาว" || message=="ที่ต้านเพลี้ยกระโดดหลังขาว");
	then
		m.addResult("ชัยนาถ1","ข้าว");
		m.addResult("สุพรรณบุรี1","ข้าว");
		m.addResult("พิษณุโลก2","ข้าว");
end
rule "22"
	when
		m:Message(message=="ต้านทานเพลี้ยจักจั่นสีเขียว" || message=="ที่ต้านทานเพลี้ยจักจั่นสีเขียว" || message=="ที่ต้านเพลี้ยจักจั่นสีเขียว");
	then
		m.addResult("พิษณุโลก2","ข้าว");
end
rule "23"
	when
		m:Message(message=="ต้านทานใบขีดโปร่งแสงปานกลาง" || message=="ที่ต้านทานใบขีดโปร่งแสงปานกลาง" || message=="ที่ต้านใบขีดโปร่งแสงปานกลาง");
	then
		m.addResult("ปราจีนบุรี1","ข้าว");
end
rule "24"
	when
		m:Message(message=="ต้านทานหนอนกอ" || message=="ที่ต้านทานหนอนกอ" || message=="ที่ต้านหนอนกอ");
	then
		m.addResult("ปราจีนบุรี1","ข้าว");
end
rule "25"
	when
		m:Message(message=="วิธีปลูกข้าวดอกมะลิ105" || message=="ช่วงเวลาที่เหมาะสมของขาวดอกมะลิ 105");
	then
		m.addResult("ในเขตชลประทานที่ไมมีปํญหาเรื่องนํ้า ควรทำนาดําหรือนาหว่านนํ้าตมแผนใหม่ โดยนาดําให้ เริ่มตกกล้ากลางเดือน กรกฎาคม ปักดําตนสิงหาคม แล้วข้าวจะออกดอกประมาณ 20 ตุลาคม และเก็บเกี่ยว ได้ประมาณ 20 พฤศจิกายนของทุกปี ส่วนนาหว่านนํ้ าตมแผนใหม่ ให้หว่านประมาณปลายเดือนกรกฎาคม ถึงตนเดือนสิงหาคม แล้วเก็บเกี่ยวในชวงปลายเดือนพฤศจิกายน ในพื้นที่ฝนตกน้อยหรือฝนลา ควรทํานาหว่านหรือนายอด โดยช่วงเวลาปลูกที่เหมาะสมอยูระหว่าง ปลายเดือนกรกฎาคมถึงต้นเดือนสิงหาคม และข้าวจะเก็บเกี่ยวได้ในช่วงปลายเดือนพฤศจิกายน","ข้อมูลข้าว");
end
rule "26"
	when
		m:Message(message=="การเตรียมดินเพื่อปลูกดอกมะลิ105");
	then
		m.addResult("นาหว่านข้าวแห้ง ในสภาพดินรวนปนทรายที่จังหวัดสุรินทร์และดินทรายปนดินรวนที่ทุ่งกุลาร้องไห้ จะเตรียมดินโดยการไถพรวนแล้วหว่านเมล็ดขาวในอัตรา 10 กิโลกรัมต่อไร่ จากนั้นคราดกลบและโปรยฟางคลุม 1000 กิโลกรัมตอไร จะทํ้าให้ผลผลิตเฉลี่ยที่ได้สูงสุดถึง 500 กิโลกรัม/ไร่ นาหว่านขาวแห้ง นาดํา จะตองไถดะทิ้งไว้ประมาณ 15 วัน จึงไถแปรอีกครั้ง เพื่อกําจัดต้นอ่อนของวัชพืชที่งอขึ้นมา ใหม่แล้วคราดเพื่อดันวัชพืชใหจมอยูใต้โคลน ในขณะเดียวกันก็เกลี่ยโคลนปรับระดับหน้าดินไปด้วย จะทําให้ระดับนํ้าในแปลงนาทวมคลุมวัชพืชได้อยางทั่วถึง","ข้อมูลข้าว");
		m.addResult("นาหวานนํ้าตมแผนใหม มีวิธีการเตรียมดินที่ยุงยากกว่า 2 วิธีที่ผ่านมา โดยเริ่มจากการไถดะทิ้งไวประมาณ 15 วัน แล้วไถแปรทิ้งไว้อีก 7 วัน จากนั้นไถแปรอีกครั้งแลวคราดเก็บเศษ วัชพืชออกใหหมด หรือ เหยียบขี้คราดดันเศษ วัชพืชต่างๆ ใหลง ไปอยู่ใต้โคลน แล้วจึงลูบเทือกใหเรียบสมํ่าเสมอ แบ่งแปลงย่อย ขนาดกว้าง 3-5 เมตร ทิ้งไว้ 1 คืน แลวจึงหวานเมล็ด หลังจาก นั้น 4-5 วันให้ทยอยปลอยนํ้าเข้าท่วมหนาดิน เพื่อคลุมวัชพืชที่ งอกตามระดับความสูงของนํ้าจนถึงระดับประมาณ 10-15 เซนติเมตร ต้นขาวจะเจริญเติบโตพอที่จะคลุมวัชพืชได้","ข้อมูลข้าว");
		m.addResult("นายอด เปนวิธีที่ไม่นิยมปลูกมากนัก แต่ถ้าจําเป็นจะต้องปลูกด้วยวิธีนี้ ในชวงเตรียมดินจะต้องกําจัดวัชพืชออกให้หมด และหลังจากหยอดเมล็ดขาวแล้วควรคลุมฟางทับในอัตรา 1000 กิโลกรัมต่อไร และ เมื่อมีโอกาสได้รับนํ้าฝนจะตองเก็บกักนํ้าใหทวมวัชพืช เพื่อกําจัดวัชพืชที่งอกมาใหม่","ข้อมูลข้าว");
end
rule "27"
	when
		m:Message(message=="ข้าวขาวดอกมะลิ105ไม่ต้านทาน" || message=="ข้าวขาวดอกมะลิ105อ่อนเเอต่อ");
	then
		m.addResult("ไหม้","โรค");
		m.addResult("คอรวงเนา","โรค");
		m.addResult("ไหม้","โรค");
		m.addResult("คอรวงเน่า","โรค");
		m.addResult("ใบหงิก","โรค");
		m.addResult("ขอบใบแห้ง","โรค");
		m.addResult("ใบจุดสีนํ้าตาล","โรค");
end
rule "28"
	when
		m:Message(message=="กรุงเทพ" || message=="ปลูกได้ที่กรุงเทพ" || message=="ปลูกที่กรุงเทพ");
	then
		m.addResult("สุพรรณบุรี1","ข้าว");
		m.addResult("สุพรรณบุรี3","ข้าว");
		m.addResult("สุพรรณบุรี60","ข้าว");
		m.addResult("พิษณุโลก2","ข้าว");
		m.addResult("ชัยนาท1","ข้าว");
		m.addResult("ปทุมธานี1","ข้าว");
end
rule "29"
	when
		m:Message(message=="กำแพงเพชร");
	then
		m.addResult("สุพรรณบุรี1","ข้าว");
		m.addResult("พิษณุโลก2","ข้าว");
		m.addResult("ขาวดอกมะลิ105","ข้าว");
		m.addResult("ชัยนาท1","ข้าว");
end
rule "30"
	when
		m:Message(message=="ชัยนาท");
	then
		m.addResult("สุพรรณบุรี2","ข้าว");
		m.addResult("พิษณุโลก2","ข้าว");
		m.addResult("ชัยนาท1","ข้าว");
		m.addResult("ชัยนาท80","ข้าว");
end
rule "31"
	when
		m:Message(message=="นครนายก");
	then
		m.addResult("สุพรรณบุรี1","ข้าว");
		m.addResult("สุพรรณบุรี60","ข้าว");
		m.addResult("พิษณุโลก2","ข้าว");
		m.addResult("ขาวดอกมะลิ105","ข้าว");
		m.addResult("ชัยนาท1","ข้าว");
		m.addResult("ปทุมธานี1","ข้าว");
end
rule "32"
	when
		m:Message(message=="นครปฐม");
	then
		m.addResult("สุพรรณบุรี1","ข้าว");
		m.addResult("สุพรรณบุรี3","ข้าว");
		m.addResult("สุพรรณบุรี60","ข้าว");
		m.addResult("ปทุมธานี1","ข้าว");
end
rule "33"
	when
		m:Message(message=="นครสวรรค์");
	then
		m.addResult("สุพรรณบุรี1","ข้าว");
		m.addResult("ขาวดอกมะลิ105","ข้าว");
end
rule "34"
	when
		m:Message(message=="นนทบุรี");
	then
		m.addResult("สุพรรณบุรี1","ข้าว");
		m.addResult("สุพรรณบุรี3","ข้าว");
		m.addResult("สุพรรณบุรี60","ข้าว");
		m.addResult("ชัยนาท1","ข้าว");
		m.addResult("ปทุมธานี1","ข้าว");
end
rule "35"
	when
		m:Message(message=="ปทุมธานี");
	then
		m.addResult("สุพรรณบุรี1","ข้าว");
		m.addResult("พิษณุโลก2","ข้าว");
		m.addResult("ชัยนาท1","ข้าว");
		m.addResult("ปทุมธานี1","ข้าว");
end
rule "36"
	when
		m:Message(message=="พิจิตร");
	then
		m.addResult("สุพรรณบุรี1","ข้าว");
		m.addResult("ขาวดอกมะลิ105","ข้าว");
		m.addResult("ปทุมธานี80","ข้าว");
		m.addResult("ชัยนาท80","ข้าว");
		m.addResult("ขาวกอเดียว","ข้าว");
end
rule "37"
	when
		m:Message(message=="พิษณุโลก");
	then
		m.addResult("สุพรรณบุรี1","ข้าว");
		m.addResult("พิษณุโลก2","ข้าว");
		m.addResult("ขาวดอกมะลิ105","ข้าว");
		m.addResult("ชัยนาท1","ข้าว");
		m.addResult("ปทุมธานี80","ข้าว");
end
rule "38"
	when
		m:Message(message=="เพชรบูรณ์");
	then
		m.addResult("ปทุมธานี80","ข้าว");
		m.addResult("ชัยนาท80","ข้าว");
end
rule "39"
	when
		m:Message(message=="ลพบุรี");
	then
		m.addResult("ปทุมธานี80","ข้าว");
		m.addResult("หลวงประทาน","ข้าว");
		m.addResult("นางมล","ข้าว");
		m.addResult("กข43","ข้าว");
		m.addResult("ขาวเศรษฐี","ข้าว");
		m.addResult("ห้ารวง","ข้าว");
		m.addResult("ปิ่นแก้ว","ข้าว");
end
rule "40"
	when
		m:Message(message=="สมุทรปราการ");
	then
		m.addResult("ปทุมธานี80","ข้าว");
		m.addResult("หลวงประทาน","ข้าว");
		m.addResult("นางมล","ข้าว");
		m.addResult("กข43","ข้าว");
		m.addResult("ขาวเศรษฐี","ข้าว");
		m.addResult("ห้ารวง","ข้าว");
		m.addResult("ปิ่นแก้ว","ข้าว");
end
rule "41"
	when
		m:Message(message=="สมุทรสงคราม");
	then
		m.addResult("ปทุมธานี80","ข้าว");
end
rule "42"
	when
		m:Message(message=="สระบุรี");
	then
		m.addResult("สุพรรณบุรี1","ข้าว");
		m.addResult("พิษณุโลก2","ข้าว");
		m.addResult("ขาวดอกมะลิ105","ข้าว");
		m.addResult("ปทุมธานี1","ข้าว");
		m.addResult("ปทุมธานี80","ข้าว");
		m.addResult("ขาวตาแห้ง17","ข้าว");
		m.addResult("เหลืองพานทอง","ข้าว");
		m.addResult("รังสิต80","ข้าว");
end
rule "43"
	when
		m:Message(message=="สิงห์บุรี");
	then
		m.addResult("สุพรรณบุรี1","ข้าว");
		m.addResult("ปทุมธานี1","ข้าว");
		m.addResult("ปทุมธานี80","ข้าว");
end
rule "44"
	when
		m:Message(message=="สุโขทัย");
	then
		m.addResult("ชัยนาท1","ข้าว");
		m.addResult("ปทุมธานี80","ข้าว");
		m.addResult("กข41","ข้าว");
		m.addResult("ชัยนาท80","ข้าว");
end
rule "45"
	when
		m:Message(message=="สุพรรณบุรี");
	then
		m.addResult("สุพรรณบุรี1","ข้าว");
		m.addResult("สุพรรณบุรี2","ข้าว");
		m.addResult("สุพรรณบุรี60","ข้าว");
		m.addResult("พิษณุโลก2","ข้าว");
		m.addResult("ปทุมธานี1","ข้าว");
		m.addResult("ปทุมธานี80","ข้าว");
		m.addResult("กข41","ข้าว");
end
rule "46"
	when
		m:Message(message=="อยุธยา");
	then
		m.addResult("ปทุมธานี80","ข้าว");
		m.addResult("หลวงประทาน","ข้าว");
		m.addResult("นางมล","ข้าว");
		m.addResult("กข43","ข้าว");
		m.addResult("ขาวเศรษฐี","ข้าว");
		m.addResult("ห้ารวง","ข้าว");
		m.addResult("ปิ่นแก้ว","ข้าว");
end
rule "47"
	when
		m:Message(message=="อ่างทอง");
	then
		m.addResult("สุพรรณบุรี1","ข้าว");
		m.addResult("สุพรรณบุรี2","ข้าว");
		m.addResult("พิษณุโลก2","ข้าว");
		m.addResult("ชัยนาท1","ข้าว");
		m.addResult("ปทุมธานี1","ข้าว");
		m.addResult("ปทุมธานี80","ข้าว");
		m.addResult("เหลืองปะทิว123","ข้าว");
end
rule "48"
	when
		m:Message(message=="ที่ต้องการชลประทาน" || message=="ต้องการชลประทาน" || message=="ชลประทาน");
	then
		m.addResult("สุพรรณบุรี1","ข้าว");
		m.addResult("สุพรรณบุรี2","ข้าว");
		m.addResult("สุพรรณบุรี3","ข้าว");
		m.addResult("สุพรรณบุรี60","ข้าว");
		m.addResult("พิษณุโลก2","ข้าว");
		m.addResult("ชัยนาท1","ข้าว");
		m.addResult("ปทุมธานี1","ข้าว");
		m.addResult("ปทุมธานี80","ข้าว");
		m.addResult("กข41","ข้าว");
		m.addResult("ชัยนาท80","ข้าว");
		m.addResult("กข43","ข้าว");
end
rule "49"
	when
		m:Message(message=="ไม่ต้องการชลประทาน" || message=="ที่ไม่ต้องการชลประทาน");
	then
		m.addResult("ขาวดอกมะลิ105","ข้าว");
		m.addResult("ขาวตาแห้ง17","ข้าว");
		m.addResult("เหลืองพานทอง","ข้าว");
		m.addResult("รังสิต80","ข้าว");
		m.addResult("เหลืองปะทิว123","ข้าว");
		m.addResult("หลวงประทาน","ข้าว");
		m.addResult("นางมล","ข้าว");
		m.addResult("ขาวเศรษฐี","ข้าว");
		m.addResult("ห้ารวง","ข้าว");
		m.addResult("ปิ่นแก้ว","ข้าว");
		m.addResult("ขาวกอเดียว","ข้าว");
end
rule "50"
	when
		m:Message(message=="ใบขีดสีน้ำตาล" || message=="ที่ต้านทานโรคใบขีดสีน้ำตาล" || message=="ต้านทานโรคใบขีดสีน้ำตาล");
	then
		m.addResult("สุพรรณบุรี3","ข้าว");
		m.addResult("สุพรรณบุรี60","ข้าว");
		m.addResult("พิษณุโลก2","ข้าว");
		m.addResult("ขาวดอกมะลิ105","ข้าว");
		m.addResult("ชัยนาท1","ข้าว");
		m.addResult("ปทุมธานี1","ข้าว");
		m.addResult("ปทุมธานี80","ข้าว");
		m.addResult("ขาวตาแห้ง17","ข้าว");
		m.addResult("เหลืองพานทอง","ข้าว");
		m.addResult("รังสิต80","ข้าว");
		m.addResult("กข41","ข้าว");
		m.addResult("ชัยนาท80","ข้าว");
		m.addResult("เหลืองปะทิว123","ข้าว");
		m.addResult("หลวงประทาน","ข้าว");
		m.addResult("นางมล","ข้าว");
		m.addResult("กข43","ข้าว");
		m.addResult("ขาวเศรษฐี","ข้าว");
		m.addResult("ห้ารวง","ข้าว");
		m.addResult("ปิ่นแก้ว","ข้าว");
		m.addResult("ขาวกอเดียว","ข้าว");
end
rule "51"
	when
		m:Message(message=="ที่ต้านทานโรคกาบใบเน่า" || message=="ต้านทานโรคกาบใบเน่า" || message=="โรคกาบใบเน่า");
	then
		m.addResult("สุพรรณบุรี1","ข้าว");
		m.addResult("สุพรรณบุรี3","ข้าว");
		m.addResult("สุพรรณบุรี60","ข้าว");
		m.addResult("พิษณุโลก2","ข้าว");
		m.addResult("ขาวดอกมะลิ105","ข้าว");
		m.addResult("ชัยนาท1","ข้าว");
		m.addResult("ปทุมธานี1","ข้าว");
		m.addResult("ปทุมธานี80","ข้าว");
		m.addResult("ขาวตาแห้ง17","ข้าว");
		m.addResult("เหลืองพานทอง","ข้าว");
		m.addResult("รังสิต80","ข้าว");
		m.addResult("กข41","ข้าว");
		m.addResult("ชัยนาท80","ข้าว");
		m.addResult("เหลืองปะทิว123","ข้าว");
		m.addResult("หลวงประทาน","ข้าว");
		m.addResult("นางมล","ข้าว");
		m.addResult("กข43","ข้าว");
		m.addResult("ขาวเศรษฐี","ข้าว");
		m.addResult("ห้ารวง","ข้าว");
		m.addResult("ขาวกอเดียว","ข้าว");
end
rule "52"
	when
		m:Message(message=="ใบหงิก" || message=="ต้านทานโรคใบหงิก" || message=="ที่ต้านทานโรคใบหงิก");
	then
		m.addResult("สุพรรณบุรี1","ข้าว");
		m.addResult("สุพรรณบุรี2","ข้าว");
		m.addResult("สุพรรณบุรี3","ข้าว");
		m.addResult("สุพรรณบุรี60","ข้าว");
		m.addResult("ชัยนาท1","ข้าว");
		m.addResult("เหลืองพานทอง","ข้าว");
		m.addResult("รังสิต80","ข้าว");
		m.addResult("กข41","ข้าว");
		m.addResult("ชัยนาท80","ข้าว");
		m.addResult("เหลืองปะทิว123","ข้าว");
		m.addResult("หลวงประทาน","ข้าว");
		m.addResult("นางมล","ข้าว");
		m.addResult("กข43","ข้าว");
		m.addResult("ขาวเศรษฐี","ข้าว");
		m.addResult("ห้ารวง","ข้าว");
		m.addResult("ขาวกอเดียว","ข้าว");
end
rule "53"
	when
		m:Message(message=="ใบจุดสีน้ำตาล" || message=="ที่ต้านทานโรคใบจุดสีน้ำตาล" || message=="ต้านทานโรคใบจุดสีน้ำตาล");
	then
		m.addResult("สุพรรณบุรี1","ข้าว");
		m.addResult("สุพรรณบุรี2","ข้าว");
		m.addResult("พิษณุโลก2","ข้าว");
		m.addResult("ขาวดอกมะลิ105","ข้าว");
		m.addResult("ชัยนาท1","ข้าว");
		m.addResult("ปทุมธานี1","ข้าว");
		m.addResult("ปทุมธานี80","ข้าว");
		m.addResult("ขาวตาแห้ง17","ข้าว");
		m.addResult("เหลืองพานทอง","ข้าว");
		m.addResult("รังสิต80","ข้าว");
		m.addResult("กข41","ข้าว");
		m.addResult("ชัยนาท80","ข้าว");
		m.addResult("เหลืองปะทิว123","ข้าว");
		m.addResult("หลวงประทาน","ข้าว");
		m.addResult("นางมล","ข้าว");
		m.addResult("กข43","ข้าว");
		m.addResult("ขาวเศรษฐี","ข้าว");
		m.addResult("ห้ารวง","ข้าว");
		m.addResult("ปิ่นแก้ว","ข้าว");
		m.addResult("ขาวกอเดียว","ข้าว");
end
rule "54"
	when
		m:Message(message=="ไหม้" || message=="ที่ต้านทานโรคไหม้" || message=="ต้านทานโรคไหม้");
	then
		m.addResult("สุพรรณบุรี1","ข้าว");
		m.addResult("สุพรรณบุรี2","ข้าว");
		m.addResult("สุพรรณบุรี3","ข้าว");
		m.addResult("สุพรรณบุรี60","ข้าว");
		m.addResult("ชัยนาท1","ข้าว");
		m.addResult("ปทุมธานี1","ข้าว");
		m.addResult("เหลืองพานทอง","ข้าว");
		m.addResult("รังสิต80","ข้าว");
		m.addResult("กข41","ข้าว");
		m.addResult("ชัยนาท80","ข้าว");
		m.addResult("หลวงประทาน","ข้าว");
		m.addResult("ขาวเศรษฐี","ข้าว");
		m.addResult("ห้ารวง","ข้าว");
end
rule "55"
	when
		m:Message(message=="แมลงบั่ว" || message=="ที่ต้านทานแมลงบั่ว" || message=="ต้านทานแมลงบั่ว");
	then
		m.addResult("สุพรรณบุรี1","ข้าว");
		m.addResult("สุพรรณบุรี2","ข้าว");
		m.addResult("สุพรรณบุรี3","ข้าว");
		m.addResult("สุพรรณบุรี60","ข้าว");
		m.addResult("ขาวดอกมะลิ105","ข้าว");
		m.addResult("ชัยนาท1","ข้าว");
		m.addResult("ปทุมธานี1","ข้าว");
		m.addResult("ปทุมธานี80","ข้าว");
		m.addResult("ขาวตาแห้ง17","ข้าว");
		m.addResult("เหลืองพานทอง","ข้าว");
		m.addResult("รังสิต80","ข้าว");
		m.addResult("กข41","ข้าว");
		m.addResult("ชัยนาท80","ข้าว");
		m.addResult("เหลืองปะทิว123","ข้าว");
		m.addResult("หลวงประทาน","ข้าว");
		m.addResult("นางมล","ข้าว");
		m.addResult("กข43","ข้าว");
		m.addResult("ขาวเศรษฐี","ข้าว");
		m.addResult("ห้ารวง","ข้าว");
		m.addResult("ปิ่นแก้ว","ข้าว");
		m.addResult("ขาวกอเดียว","ข้าว");
end
rule "56"
	when
		m:Message(message=="ใบสีส้ม" || message=="ที่ต้านทานโรคใบสีส้ม" || message=="ต้านทานโรคใบสีส้ม");
	then
		m.addResult("สุพรรณบุรี1","ข้าว");
		m.addResult("สุพรรณบุรี2","ข้าว");
		m.addResult("สุพรรณบุรี60","ข้าว");
		m.addResult("พิษณุโลก2","ข้าว");
		m.addResult("เหลืองพานทอง","ข้าว");
		m.addResult("รังสิต80","ข้าว");
		m.addResult("กข41","ข้าว");
		m.addResult("ชัยนาท80","ข้าว");
		m.addResult("หลวงประทาน","ข้าว");
		m.addResult("กข43","ข้าว");
		m.addResult("ขาวเศรษฐี","ข้าว");
		m.addResult("ห้ารวง","ข้าว");
		m.addResult("ขาวกอเดียว","ข้าว");
end
rule "57"
	when
		m:Message(message=="กาบใบแห้ง" || message=="ต้านทานโรคกาบใบแห้ง" || message=="ที่ต้านทานโรคกาบใบแห้ง");
	then
		m.addResult("สุพรรณบุรี1","ข้าว");
		m.addResult("สุพรรณบุรี2","ข้าว");
		m.addResult("สุพรรณบุรี3","ข้าว");
		m.addResult("พิษณุโลก2","ข้าว");
		m.addResult("ขาวดอกมะลิ105","ข้าว");
		m.addResult("ชัยนาท1","ข้าว");
		m.addResult("ปทุมธานี1","ข้าว");
		m.addResult("ปทุมธานี80","ข้าว");
		m.addResult("ขาวตาแห้ง17","ข้าว");
		m.addResult("เหลืองพานทอง","ข้าว");
		m.addResult("รังสิต80","ข้าว");
		m.addResult("กข41","ข้าว");
		m.addResult("ชัยนาท80","ข้าว");
		m.addResult("เหลืองปะทิว123","ข้าว");
		m.addResult("หลวงประทาน","ข้าว");
		m.addResult("นางมล","ข้าว");
		m.addResult("กข43","ข้าว");
		m.addResult("ขาวเศรษฐี","ข้าว");
		m.addResult("ห้ารวง","ข้าว");
		m.addResult("ปิ่นแก้ว","ข้าว");
		m.addResult("ขาวกอเดียว","ข้าว");
end
rule "58"
	when
		m:Message(message=="เมล็ดร่วงง่าย" || message=="ต้านทานโรคเมล็ดร่วงง่าย" || message=="ที่ต้านทานโรคเมล็ดร่วงง่าย");
	then
		m.addResult("สุพรรณบุรี1","ข้าว");
		m.addResult("สุพรรณบุรี2","ข้าว");
		m.addResult("สุพรรณบุรี3","ข้าว");
		m.addResult("สุพรรณบุรี60","ข้าว");
		m.addResult("ขาวดอกมะลิ105","ข้าว");
		m.addResult("ชัยนาท1","ข้าว");
		m.addResult("ปทุมธานี1","ข้าว");
		m.addResult("ปทุมธานี80","ข้าว");
		m.addResult("ขาวตาแห้ง17","ข้าว");
		m.addResult("เหลืองพานทอง","ข้าว");
		m.addResult("รังสิต80","ข้าว");
		m.addResult("กข41","ข้าว");
		m.addResult("ชัยนาท80","ข้าว");
		m.addResult("เหลืองปะทิว123","ข้าว");
		m.addResult("หลวงประทาน","ข้าว");
		m.addResult("นางมล","ข้าว");
		m.addResult("กข43","ข้าว");
		m.addResult("ขาวเศรษฐี","ข้าว");
		m.addResult("ห้ารวง","ข้าว");
		m.addResult("ปิ่นแก้ว","ข้าว");
		m.addResult("ขาวกอเดียว","ข้าว");
end
rule "59"
	when
		m:Message(message=="ขอบใบแห้ง" || message=="ต้านทานโรคขอบใบแห้ง" || message=="ที่ต้านทานโรคขอบใบแห้ง");
	then
		m.addResult("สุพรรณบุรี1","ข้าว");
		m.addResult("สุพรรณบุรี2","ข้าว");
		m.addResult("สุพรรณบุรี3","ข้าว");
		m.addResult("สุพรรณบุรี60","ข้าว");
		m.addResult("พิษณุโลก2","ข้าว");
		m.addResult("ปทุมธานี1","ข้าว");
		m.addResult("ปทุมธานี80","ข้าว");
		m.addResult("เหลืองพานทอง","ข้าว");
		m.addResult("รังสิต80","ข้าว");
		m.addResult("ชัยนาท80","ข้าว");
		m.addResult("เหลืองปะทิว123","ข้าว");
		m.addResult("หลวงประทาน","ข้าว");
		m.addResult("กข43","ข้าว");
		m.addResult("ขาวเศรษฐี","ข้าว");
		m.addResult("ห้ารวง","ข้าว");
end
rule "60"
	when
		m:Message(message=="ต้านทานโรคเพลี้ยกระโดดสีน้ำตาล" || message=="ที่ต้านทานโรคเพลี้ยกระโดดสีน้ำตาล" || message=="เพลี้ยกระโดดสีน้ำตาล");
	then
		m.addResult("สุพรรณบุรี1","ข้าว");
		m.addResult("สุพรรณบุรี2","ข้าว");
		m.addResult("สุพรรณบุรี3","ข้าว");
		m.addResult("สุพรรณบุรี60","ข้าว");
		m.addResult("พิษณุโลก2","ข้าว");
		m.addResult("ชัยนาท1","ข้าว");
		m.addResult("ปทุมธานี1","ข้าว");
		m.addResult("ปทุมธานี80","ข้าว");
		m.addResult("ขาวตาแห้ง17","ข้าว");
		m.addResult("หลวงประทาน","ข้าว");
		m.addResult("กข43","ข้าว");
		m.addResult("ขาวเศรษฐี","ข้าว");
		m.addResult("ห้ารวง","ข้าว");
end
rule "61"
	when
		m:Message(message=="ต้านทานโรคเพลี้ยจักจั่นเขียว" || message=="ที่ต้านทานโรคเพลี้ยจักจั่นเขียว" || message=="เพลี้ยจักจั่นเขียว");
	then
		m.addResult("สุพรรณบุรี1","ข้าว");
		m.addResult("สุพรรณบุรี2","ข้าว");
		m.addResult("สุพรรณบุรี3","ข้าว");
		m.addResult("สุพรรณบุรี60","ข้าว");
		m.addResult("พิษณุโลก2","ข้าว");
		m.addResult("ชัยนาท1","ข้าว");
		m.addResult("ปทุมธานี80","ข้าว");
		m.addResult("ขาวตาแห้ง17","ข้าว");
		m.addResult("รังสิต80","ข้าว");
		m.addResult("กข41","ข้าว");
		m.addResult("ชัยนาท80","ข้าว");
		m.addResult("หลวงประทาน","ข้าว");
		m.addResult("นางมล","ข้าว");
		m.addResult("กข43","ข้าว");
		m.addResult("ขาวเศรษฐี","ข้าว");
		m.addResult("ห้ารวง","ข้าว");
		m.addResult("ขาวกอเดียว","ข้าว");
end
rule "62"
	when
		m:Message(message=="ต้านทานหนอนกอ" || message=="ที่ต้านทานหนอนกอ" || message=="หนอนกอ");
	then
		m.addResult("สุพรรณบุรี1","ข้าว");
		m.addResult("สุพรรณบุรี2","ข้าว");
		m.addResult("สุพรรณบุรี3","ข้าว");
		m.addResult("สุพรรณบุรี60","ข้าว");
		m.addResult("พิษณุโลก2","ข้าว");
		m.addResult("ชัยนาท1","ข้าว");
		m.addResult("ปทุมธานี1","ข้าว");
		m.addResult("ปทุมธานี80","ข้าว");
		m.addResult("ขาวตาแห้ง17","ข้าว");
		m.addResult("รังสิต80","ข้าว");
		m.addResult("กข41","ข้าว");
		m.addResult("ชัยนาท80","ข้าว");
		m.addResult("หลวงประทาน","ข้าว");
		m.addResult("นางมล","ข้าว");
		m.addResult("กข43","ข้าว");
		m.addResult("ขาวเศรษฐี","ข้าว");
		m.addResult("ห้ารวง","ข้าว");
		m.addResult("ขาวกอเดียว","ข้าว");
end
rule "63"
	when
		m:Message(message=="ใบขีดโปร่งแสง" || message=="ต้านทานโรคใบขีดโปร่งแสง" || message=="ที่ต้านทานโรคใบขีดโปร่งแสง");
	then
		m.addResult("สุพรรณบุรี1","ข้าว");
		m.addResult("สุพรรณบุรี2","ข้าว");
		m.addResult("สุพรรณบุรี3","ข้าว");
		m.addResult("สุพรรณบุรี60","ข้าว");
		m.addResult("พิษณุโลก2","ข้าว");
		m.addResult("ขาวดอกมะลิ105","ข้าว");
		m.addResult("ปทุมธานี1","ข้าว");
		m.addResult("ปทุมธานี80","ข้าว");
		m.addResult("ขาวตาแห้ง17","ข้าว");
		m.addResult("เหลืองพานทอง","ข้าว");
		m.addResult("รังสิต80","ข้าว");
		m.addResult("กข41","ข้าว");
		m.addResult("ชัยนาท80","ข้าว");
		m.addResult("เหลืองปะทิว123","ข้าว");
		m.addResult("หลวงประทาน","ข้าว");
		m.addResult("นางมล","ข้าว");
		m.addResult("กข43","ข้าว");
		m.addResult("ขาวเศรษฐี","ข้าว");
		m.addResult("ห้ารวง","ข้าว");
		m.addResult("ปิ่นแก้ว","ข้าว");
		m.addResult("ขาวกอเดียว","ข้าว");
end
rule "64"
	when
		m:Message(message=="เขียวเตี้ย" || message=="ต้านทานโรคเขียวเตี้ย" || message=="ที่ต้านทานโรคเขียวเตี้ย");
	then
		m.addResult("สุพรรณบุรี1","ข้าว");
		m.addResult("สุพรรณบุรี2","ข้าว");
		m.addResult("สุพรรณบุรี3","ข้าว");
		m.addResult("สุพรรณบุรี60","ข้าว");
		m.addResult("พิษณุโลก2","ข้าว");
		m.addResult("ขาวดอกมะลิ105","ข้าว");
		m.addResult("ชัยนาท1","ข้าว");
		m.addResult("ปทุมธานี1","ข้าว");
		m.addResult("ปทุมธานี80","ข้าว");
		m.addResult("ขาวตาแห้ง17","ข้าว");
		m.addResult("เหลืองพานทอง","ข้าว");
		m.addResult("รังสิต80","ข้าว");
		m.addResult("กข41","ข้าว");
		m.addResult("ชัยนาท80","ข้าว");
		m.addResult("หลวงประทาน","ข้าว");
		m.addResult("นางมล","ข้าว");
		m.addResult("กข43","ข้าว");
		m.addResult("ขาวเศรษฐี","ข้าว");
		m.addResult("ห้ารวง","ข้าว");
		m.addResult("ปิ่นแก้ว","ข้าว");
		m.addResult("ขาวกอเดียว","ข้าว");
end
rule "65"
	when
		m:Message(message=="ภาคกลาง" || message=="อยู่ในภาคกลาง" || message=="ที่อยู่ในกลาง");
	then
		m.addResult("กรุงเทพ","จังหวัด");
		m.addResult("กำแพงเพชร","จังหวัด");
		m.addResult("ชัยนาท","จังหวัด");
		m.addResult("นครนายก","จังหวัด");
		m.addResult("นครปฐม","จังหวัด");
		m.addResult("นครสวรรค์","จังหวัด");
		m.addResult("นนทบุรี","จังหวัด");
		m.addResult("ปทุมธานี","จังหวัด");
		m.addResult("พิจิตร","จังหวัด");
		m.addResult("พิษณุโลก","จังหวัด");
		m.addResult("เพชรบูรณ์","จังหวัด");
		m.addResult("ลพบุรี","จังหวัด");
		m.addResult("สมุทรปราการ","จังหวัด");
		m.addResult("สมุทรสงคราม","จังหวัด");
		m.addResult("สระบุรี","จังหวัด");
		m.addResult("สิงห์บุรี","จังหวัด");
		m.addResult("สุโขทัย","จังหวัด");
		m.addResult("สุพรรณบุรี","จังหวัด");
		m.addResult("อยุธยา","จังหวัด");
		m.addResult("อ่างทอง","จังหวัด");
end
rule "66"
	when
		m:Message(message=="ภาคกลาง" || message=="ที่ปลูกได้ในภาคกลาง" || message=="ปลูกภาคกลาง" || message=="ปลูกได้ในภาคกลาง");
	then
		m.addResult("สุพรรณบุรี1","ข้าว");
		m.addResult("สุพรรณบุรี3","ข้าว");
		m.addResult("สุพรรณบุรี60","ข้าว");
		m.addResult("พิษณุโลก2","ข้าว");
		m.addResult("ชัยนาท1","ข้าว");
		m.addResult("ปทุมธานี1","ข้าว");
		m.addResult("ขาวดอกมะลิ105","ข้าว");
		m.addResult("สุพรรณบุรี2","ข้าว");
		m.addResult("ชัยนาท80","ข้าว");
		m.addResult("ปทุมธานี80","ข้าว");
		m.addResult("ขาวกอเดียว","ข้าว");
		m.addResult("หลวงประทาน","ข้าว");
		m.addResult("นางมล","ข้าว");
		m.addResult("กข43","ข้าว");
		m.addResult("ขาวเศรษฐี","ข้าว");
		m.addResult("ห้ารวง","ข้าว");
		m.addResult("ปิ่นแก้ว","ข้าว");
		m.addResult("ขาวตาแห้ง17","ข้าว");
		m.addResult("เหลืองพานทอง","ข้าว");
		m.addResult("รังสิต80","ข้าว");
		m.addResult("กข41","ข้าว");
		m.addResult("เหลืองปะทิว123","ข้าว");
end
rule "67"
	when
		m:Message(message=="ที่สามารถปลูกสุพรรณบุรี1" || message=="สามารถปลูกสุพรรณบุรี1" || message=="ปลูกสุพรรณบุรี1" || message=="สุพรรณบุรี1");
	then
		m.addResult("กรุงเทพ","จังหวัด");
		m.addResult("กำแพงเพชร","จังหวัด");
		m.addResult("นครปฐม","จังหวัด");
		m.addResult("นครสวรรค์","จังหวัด");
		m.addResult("นครนายก","จังหวัด");
		m.addResult("นนทบุรี","จังหวัด");
		m.addResult("ปทุมธานี","จังหวัด");
		m.addResult("พิจิตร","จังหวัด");
		m.addResult("พิษณุโลก","จังหวัด");
		m.addResult("สระบุรี","จังหวัด");
		m.addResult("สิงห์บุรี","จังหวัด");
		m.addResult("สุพรรณบุรี","จังหวัด");
		m.addResult("อ่างทอง","จังหวัด");
end
rule "68"
	when
		m:Message(message=="ที่สามารถปลูกสุพรรณบุรี2" || message=="สามารถปลูกสุพรรณบุรี2" || message=="ปลูกสุพรรณบุรี2" || message=="สุพรรณบุรี2");
	then
		m.addResult("ชัยนาท","จังหวัด");
		m.addResult("สุพรรณบุรี","จังหวัด");
		m.addResult("อ่างทอง","จังหวัด");
end
rule "69"
	when
		m:Message(message=="ที่สามารถปลูกสุพรรณบุรี3" || message=="สามารถปลูกสุพรรณบุรี3" || message=="ปลูกสุพรรณบุรี3" || message=="สุพรรณบุรี3");
	then
		m.addResult("กรุงเทพ","จังหวัด");
		m.addResult("นครปฐม","จังหวัด");
		m.addResult("นนทบุรี","จังหวัด");
end
rule "70"
	when
		m:Message(message=="ที่สามารถปลูกสุพรรณบุรี60" || message=="สามารถปลูกสุพรรณบุรี60" || message=="ปลูกสุพรรณบุรี60" || message=="สุพรรณบุรี60");
	then
		m.addResult("กรุงเทพ","จังหวัด");
		m.addResult("นครนายก","จังหวัด");
		m.addResult("นครปฐม","จังหวัด");
		m.addResult("นนทบุรี","จังหวัด");
		m.addResult("สุพรรณบุรี","จังหวัด");
end
rule "71"
	when
		m:Message(message=="ที่สามารถปลูกพิษณุโลก2" || message=="สามารถปลูกพิษณุโลก2" || message=="ปลูกพิษณุโลก2" || message=="พิษณุโลก2");
	then
		m.addResult("กรุงเทพ","จังหวัด");
		m.addResult("กำแพงเพชร","จังหวัด");
		m.addResult("ชัยนาท","จังหวัด");
		m.addResult("นครนายก","จังหวัด");
		m.addResult("ปทุมธานี","จังหวัด");
		m.addResult("พิษณุโลก","จังหวัด");
		m.addResult("สระบุรี","จังหวัด");
		m.addResult("สุพรรณบุรี","จังหวัด");
		m.addResult("อ่างทอง","จังหวัด");
end
rule "72"
	when
		m:Message(message=="ที่สามารถปลูกชัยนาท1" || message=="สามารถปลูกชัยนาท1" || message=="ปลูกชัยนาท1" || message=="ชัยนาท1");
	then
		m.addResult("กรุงเทพ","จังหวัด");
		m.addResult("กำแพงเพชร","จังหวัด");
		m.addResult("ชัยนาท","จังหวัด");
		m.addResult("นครนายก","จังหวัด");
		m.addResult("นนทบุรี","จังหวัด");
		m.addResult("ปทุมธานี","จังหวัด");
		m.addResult("พิษณุโลก","จังหวัด");
		m.addResult("สุโขทัย","จังหวัด");
		m.addResult("อ่างทอง","จังหวัด");
end
rule "73"
	when
		m:Message(message=="ที่สามารถปลูกชัยนาท80" || message=="สามารถปลูกชัยนาท80" || message=="ปลูกชัยนาท80" || message=="ชัยนาท80");
	then
		m.addResult("ชัยนาท","จังหวัด");
		m.addResult("พิจิตร","จังหวัด");
		m.addResult("เพชรบูรณ์","จังหวัด");
		m.addResult("สุโขทัย","จังหวัด");
end
rule "74"
	when
		m:Message(message=="ที่สามารถปลูกปทุมธานี1" || message=="สามารถปลูกปทุมธานี1" || message=="ปลูกปทุมธานี1" || message=="ปทุมธานี1");
	then
		m.addResult("กรุงเทพ","จังหวัด");
		m.addResult("นครนายก","จังหวัด");
		m.addResult("นครปฐม","จังหวัด");
		m.addResult("นนทบุรี","จังหวัด");
		m.addResult("ปทุมธานี","จังหวัด");
		m.addResult("สระบุรี","จังหวัด");
		m.addResult("สิงห์บุรี","จังหวัด");
		m.addResult("สุพรรณบุรี","จังหวัด");
		m.addResult("อ่างทอง","จังหวัด");
end
rule "75"
	when
		m:Message(message=="ที่สามารถปลูกปทุมธานี80" || message=="สามารถปลูกปทุมธานี80" || message=="ปลูกปทุมธานี80" || message=="ปทุมธานี80");
	then
		m.addResult("พิจิตร","จังหวัด");
		m.addResult("พิษณุโลก","จังหวัด");
		m.addResult("เพชรบูรณ์","จังหวัด");
		m.addResult("ลพบุรี","จังหวัด");
		m.addResult("สมุทรปราการ","จังหวัด");
		m.addResult("สมุทรสงคราม","จังหวัด");
		m.addResult("สระบุรี","จังหวัด");
		m.addResult("สิงห์บุรี","จังหวัด");
		m.addResult("สุโขทัย","จังหวัด");
		m.addResult("สุพรรณบุรี","จังหวัด");
		m.addResult("อยุธยา","จังหวัด");
		m.addResult("อ่างทอง","จังหวัด");
end
rule "76"
	when
		m:Message(message=="ที่สามารถปลูกขาวดอกมะลิ105" || message=="สามารถปลูกขาวดอกมะลิ105" || message=="ปลูกขาวดอกมะลิ105" || message=="ขาวดอกมะลิ105");
	then
		m.addResult("กำแพงเพชร","จังหวัด");
		m.addResult("นครนายก","จังหวัด");
		m.addResult("นครสววรค์","จังหวัด");
		m.addResult("พิจิตร","จังหวัด");
		m.addResult("พิษณุโลก","จังหวัด");
		m.addResult("สระบุรี","จังหวัด");
end
rule "77"
	when
		m:Message(message=="ที่สามารถปลูกกข41" || message=="สามารถปลูกกข41" || message=="ปลูกกข41" || message=="กข41");
	then
		m.addResult("สุโขทัย","จังหวัด");
		m.addResult("สุพรรณบุรี","จังหวัด");
		m.addResult("ตาก","จังหวัด");
end
rule "78"
	when
		m:Message(message=="ที่สามารถปลูกกข43" || message=="สามารถปลูกกข43" || message=="ปลูกกข43" || message=="กข43");
	then
		m.addResult("ลพบุรี","จังหวัด");
		m.addResult("สมุทรปราการ","จังหวัด");
		m.addResult("อยุธยา","จังหวัด");
end
rule "79"
	when
		m:Message(message=="ที่สามารถปลูกขาวกอเดียว" || message=="สามารถปลูกขาวกอเดียว" || message=="ปลูกขาวกอเดียว" || message=="ขาวกอเดียว");
	then
		m.addResult("พิจิตร","จังหวัด");
end
rule "80"
	when
		m:Message(message=="ที่สามารถปลูกหลวงประทาน" || message=="สามารถปลูกหลวงประทาน" || message=="ปลูกหลวงประทาน" || message=="หลวงประทาน");
	then
		m.addResult("ลพบุรี","จังหวัด");
		m.addResult("สมุทรปราการ","จังหวัด");
		m.addResult("อยุธยา","จังหวัด");
end
rule "81"
	when
		m:Message(message=="ที่สามารถปลูกนางมล" || message=="สามารถปลูกนางมล" || message=="ปลูกนางมล" || message=="นางมล");
	then
		m.addResult("ลพบุรี","จังหวัด");
		m.addResult("สมุทรปราการ","จังหวัด");
		m.addResult("อยุธยา","จังหวัด");
end
rule "82"
	when
		m:Message(message=="ที่สามารถปลูกขาวเศรษฐี" || message=="สามารถปลูกขาวเศรษฐี" || message=="ปลูกขาวเศรษฐี" || message=="ขาวเศรษฐี");
	then
		m.addResult("ลพบุรี","จังหวัด");
		m.addResult("สมุทรปราการ","จังหวัด");
		m.addResult("อยุธยา","จังหวัด");
end
rule "83"
	when
		m:Message(message=="ที่สามารถปลูกห้ารวง" || message=="สามารถปลูกห้ารวง" || message=="ปลูกห้ารวง" || message=="ห้ารวง");
	then
		m.addResult("ลพบุรี","จังหวัด");
		m.addResult("สมุทรปราการ","จังหวัด");
		m.addResult("อยุธยา","จังหวัด");
end
rule "84"
	when
		m:Message(message=="ที่สามารถปลูกปิ่นแก้ว" || message=="สามารถปลูกปิ่นแก้ว" || message=="ปลูกปิ่นแก้ว" || message=="ปิ่นแก้ว");
	then
		m.addResult("ลพบุรี","จังหวัด");
		m.addResult("สมุทรปราการ","จังหวัด");
		m.addResult("อยุธยา","จังหวัด");
end
rule "85"
	when
		m:Message(message=="ที่สามารถปลูกขาวตาแห้ง17" || message=="สามารถปลูกขาวตาแห้ง17" || message=="ปลูกขาวตาแห้ง17" || message=="ขาวตาแห้ง17");
	then
		m.addResult("สระบุรี","จังหวัด");
end
rule "86"
	when
		m:Message(message=="ที่สามารถปลูกเหลืองพานทอง" || message=="สามารถปลูกเหลืองพานทอง" || message=="ปลูกเหลืองพานทอง" || message=="เหลืองพานทอง");
	then
		m.addResult("สระบุรี","จังหวัด");
end
rule "87"
	when
		m:Message(message=="ที่สามารถปลูกรังสิต80" || message=="สามารถปลูกรังสิต80" || message=="ปลูกรังสิต80" || message=="รังสิต80");
	then
		m.addResult("สระบุรี","จังหวัด");
end
rule "88"
	when
		m:Message(message=="ที่สามารถปลูกเหลืองปะทิว123" || message=="สามารถปลูกเหลืองปะทิว123" || message=="ปลูกเหลืองปะทิว123" || message=="เหลืองปะทิว123");
	then
		m.addResult("อ่างทอง","จังหวัด");
end
rule "89"
	when
		m:Message(message=="นาน้ำฝน" || message=="เกิดในนาน้ำฝน" || message=="ที่เกิดในนาน้ำฝน" || message=="ในนาน้ำฝน");
	then
		m.addResult("ใบจุดสีน้ำตาล","โรค");
		m.addResult("ขอบใบแห้ง","โรค");
		m.addResult("ไหม้","โรค");
		m.addResult("ใบสีส้ม","โรค");
end
rule "90"
	when
		m:Message(message=="ที่เกิดในนาชลประทาน" || message=="เกิดในนาชลประทาน" || message=="ในนาชลประทาน" || message=="นาชลประทาน");
	then
		m.addResult("ใบจุดสีน้ำตาล","โรค");
		m.addResult("เมล็ดด่าง","โรค");
		m.addResult("ขอบใบแห้ง","โรค");
		m.addResult("กาบใบแห้ง","โรค");
		m.addResult("ใบหงิก","โรค");
		m.addResult("ใบขีดโปร่งแสง","โรค");
		m.addResult("ใบสีส้ม","โรค");
end
rule "91"
	when
		m:Message(message=="ต้นกล้า" || message=="เกิดที่ต้นกล้า" || message=="ที่ต้นกล้า");
	then
		m.addResult("ขอบใบแห้ง","โรค");
end
rule "92"
	when
		m:Message(message=="ใบ" || message=="ที่ใบ" || message=="เกิดที่ใบ");
	then
		m.addResult("ใบจุดสีน้ำตาล","โรค");
		m.addResult("ขอบใบแห้ง","โรค");
		m.addResult("กาบใบแห้ง","โรค");
		m.addResult("ไหม้","โรค");
		m.addResult("ใบหงิก","โรค");
		m.addResult("ใบขีดโปร่งแสง","โรค");
		m.addResult("ใบสีส้ม","โรค");
end
rule "93"
	when
		m:Message(message=="ลำต้น" || message=="ที่ลำต้น" || message=="เกิดที่ลำต้น");
	then
		m.addResult("ไหม้","โรค");
		m.addResult("ใบหงิก","โรค");
		m.addResult("ใบสีส้ม","โรค");
end
rule "94"
	when
		m:Message(message=="เมล็ด" || message=="ที่เมล็ด" || message=="เกิดที่เมล็ด");
	then
		m.addResult("ใบจุดสีน้ำตาล","โรค");
		m.addResult("เมล็ดด่าง","โรค");
		m.addResult("ไหม้","โรค");
		m.addResult("ใบหงิก","โรค");
end
rule "95"
	when
		m:Message(message=="ดอกข้าว" || message=="ที่ดอกข้าว" || message=="เกิดที่ดอกข้าว");
	then
		m.addResult("เมล็ดด่าง","โรค");
end
rule "96"
	when
		m:Message(message=="กล้า" || message=="ระยะกล้า" || message=="เมื่อกล้า");
	then
		m.addResult("ขอบใบแห้ง","โรค");
		m.addResult("ไหม้","โรค");
		m.addResult("ใบหงิก","โรค");
		m.addResult("ใบสีส้ม","โรค");
end
rule "97"
	when
		m:Message(message=="แตกกอ" || message=="ระยะแตกกอ" || message=="เมื่อแตกกอ");
	then
		m.addResult("ใบจุดสีน้ำตาล","โรค");
		m.addResult("ขอบใบแห้ง","โรค");
		m.addResult("กาบใบแห้ง","โรค");
		m.addResult("ไหม้","โรค");
		m.addResult("ใบหงิก","โรค");
		m.addResult("ใบขีดโปร่งแสง","โรค");
		m.addResult("ใบสีส้ม","โรค");
end
rule "98"
	when
		m:Message(message=="ออกรวง" || message=="ระยะออกรวง" || message=="เมื่อออกรวง");
	then
		m.addResult("เมล็ดด่าง","โรค");
		m.addResult("ขอบใบแห้ง","โรค");
		m.addResult("ไหม้","โรค");
		m.addResult("ใบขีดโปร่งแสง","โรค");
end
rule "99"
	when
		m:Message(message=="ตั้งท้อง" || message=="ระยะตั้งท้อง" || message=="เมื่อตั้งท้อง");
	then
		m.addResult("ใบหงิก","โรค");
		m.addResult("ใบสีส้ม","โรค");
end
rule "100"
	when
		m:Message(message=="เก็บเกี่ยว" || message=="เมื่อเก็บเกี่ยว" || message=="ระยะเก็บเกี่ยว");
	then
		m.addResult("เมล็ดด่าง","โรค");
		m.addResult("กาบใบแห้ง","โรค");
end
rule "101"
	when
		m:Message(message=="สุพรรณบุรี1" || message=="ที่เกิดในสุพรรณบุรี1" || message=="เกิดในสุพรรณบุรี1");
	then
		m.addResult("ใบจุดสีน้ำตาล","โรค");
		m.addResult("เมล็ดด่าง","โรค");
end
rule "102"
	when
		m:Message(message=="สุพรรณบุรี3" || message=="ที่เกิดในสุพรรณบุรี3" || message=="เกิดในสุพรรณบุรี3");
	then
		m.addResult("ใบจุดสีน้ำตาล","โรค");
		m.addResult("ใบสีส้ม","โรค");
end
rule "103"
	when
		m:Message(message=="สุพรรณบุรี60" || message=="ที่เกิดในสุพรรณบุรี60" || message=="เกิดในสุพรรณบุรี60");
	then
		m.addResult("ใบจุดสีน้ำตาล","โรค");
		m.addResult("เมล็ดด่าง","โรค");
		m.addResult("กาบใบแห้ง","โรค");
end
rule "104"
	when
		m:Message(message=="พิษณุโลก2" || message=="ที่เกิดในพิษณุโลก2" || message=="เกิดในพิษณุโลก2");
	then
		m.addResult("ไหม้","โรค");
		m.addResult("ใบหงิก","โรค");
end
rule "105"
	when
		m:Message(message=="ขาวดอกมะลิ105" || message=="ที่เกิดในขาวดอกมะลิ105" || message=="เกิดในขาวดอกมะลิ105");
	then
		m.addResult("ขอบใบแห้ง","โรค");
		m.addResult("ไหม้","โรค");
		m.addResult("ใบหงิก","โรค");
end
rule "106"
	when
		m:Message(message=="ชัยนาท1" || message=="ที่เกิดในชัยนาท1" || message=="เกิดในชัยนาท1");
	then
		m.addResult("ขอบใบแห้ง","โรค");
		m.addResult("ใบขีดโปร่งแสง","โรค");
		m.addResult("ใบสีส้ม","โรค");
end
rule "107"
	when
		m:Message(message=="เหลืองประทิว123" || message=="ที่เกิดในเหลืองประทิว123" || message=="เกิดในเหลืองประทิว123");
	then
		m.addResult("ไหม้","โรค");
		m.addResult("เขียวเตี้ย","โรค");
		m.addResult("ใบสีส้ม","โรค");
end
rule "108"
	when
		m:Message(message=="นางมล" || message=="ที่เกิดในนางมล" || message=="เกิดในนางมล");
	then
		m.addResult("เมล็ดร่วงง่าย","โรค");
		m.addResult("ไหม้","โรค");
		m.addResult("ขอบใบแห้ง","โรค");
		m.addResult("ใบสีส้ม","โรค");
end
rule "109"
	when
		m:Message(message=="ปทุมธานี1" || message=="ที่เกิดในปทุมธานี1" || message=="เกิดในปทุมธานี1");
	then
		m.addResult("ใบหงิก","โรค");
		m.addResult("ใบสีส้ม","โรค");
end
rule "110"
	when
		m:Message(message=="ปทุมธานี80" || message=="ที่เกิดในปทุมธานี80" || message=="เกิดในปทุมธานี80");
	then
		m.addResult("ใบหงิก","โรค");
		m.addResult("ใบสีส้ม","โรค");
		m.addResult("ไหม้","โรค");
end
rule "111"
	when
		m:Message(message=="ขาวตาแห้ง17" || message=="ที่เกิดในขาวตาแห้ง17" || message=="เกิดในขาวตาแห้ง17");
	then
		m.addResult("ขอบใบแห้ง","โรค");
		m.addResult("ไหม้","โรค");
		m.addResult("ใบสีส้ม","โรค");
		m.addResult("ใบหงิก","โรค");
end
rule "112"
	when
		m:Message(message=="ขาวกอเดียว" || message=="ที่เกิดในขาวกอเดียว" || message=="เกิดในขาวกอเดียว");
	then
		m.addResult("ขอบใบแห้ง","โรค");
		m.addResult("ไหม้","โรค");
end
rule "113"
	when
		m:Message(message=="กข41" || message=="ที่เกิดในกข41" || message=="เกิดในกข41");
	then
		m.addResult("ขอบใบแห้ง","โรค");
end
rule "114"
	when
		m:Message(message=="กข43" || message=="ที่เกิดในกข43" || message=="เกิดในกข43");
	then
		m.addResult("ไหม้","โรค");
end
rule "115"
	when
		m:Message(message=="ปิ่นแก้ว" || message=="ที่เกิดในปิ่นแก้ว" || message=="เกิดในปิ่นแก้ว");
	then
		m.addResult("ขอบใบแห้ง","โรค");
		m.addResult("ไหม้","โรค");
		m.addResult("ใบสีส้ม","โรค");
		m.addResult("กาบใบแห้ง","โรค");
		m.addResult("ใบหงิก","โรค");
end
rule "116"
	when
		m:Message(message=="ขาวดอกมะลิ105ไม่ต้านทาน" || message=="ขาวดอกมะลิ105อ่อนเเอต่อ");
	then
		m.addResult("เพลี้ยกระโดดสีนํ้าตาล","แมลง");
		m.addResult("เพลี้ยกระโดดสีนํ้าตาล","แมลง");
		m.addResult("หนอนกอ","แมลง");
		m.addResult("แมลงสิง","แมลง");
end
rule "117"
	when
		m:Message(message=="กข6ไม่ต้านทาน" || message=="กข6อ่อนเเอต่อ");
	then
		m.addResult("เพลี้ยกระโดดสีนํ้าตาล","แมลง");
		m.addResult("แมลงบั่ว","แมลง");
end
rule "118"
	when
		m:Message(message=="เหนียวสันป่าตองไม่ต้านทาน" || message=="เหนียวสันป่าตองอ่อนเเอต่อ");
	then
		m.addResult("เพลี้ยกระโดดสีนํ้าตาล","แมลง");
		m.addResult("แมลงบั่ว","แมลง");
end
rule "119"
	when
		m:Message(message=="ชัยนาท1ไม่ต้านทาน" || message=="ชัยนาท1อ่อนเเอต่อ");
	then
		m.addResult("ใบสีส้ม","โรค");
		m.addResult("ขอบใบแห้ง","โรค");
		m.addResult("ไหม้","โรค");
		m.addResult("ใบจุดสีน้ำตาล","โรค");
end
rule "120"
	when
		m:Message(message=="สุพรรณบุรี1ไม่ต้านทาน" || message=="สุพรรณบุรี1อ่อนเเอต่อ");
	then
		m.addResult("ใบขีดสีน้ำตาล","โรค");
end
rule "121"
	when
		m:Message(message=="พิษณุโลก2ไม่ต้านทาน" || message=="พิษณุโลก2อ่อนเเอต่อ");
	then
		m.addResult("ใบหงิก","โรค");
end
rule "122"
	when
		m:Message(message=="พิษณุโลก2ไม่ต้านทาน" || message=="พิษณุโลก2อ่อนแอต่อ");
	then
		m.addResult("แมลงบั่ว","แมลง");
		m.addResult("หนอนห่อใบข้าว","แมลง");
end
rule "123"
	when
		m:Message(message=="ปราจีนบุรี1ไม่ต้านทาน" || message=="ปราจีนบุรี1อ่อนเเอต่อ");
	then
		m.addResult("ใบสีส้ม","โรค");
end
rule "124"
	when
		m:Message(message=="ปราจีนบุรี1ไม่ต้านทาน" || message=="ปราจีนบุรี1อ่อนแอต่อ");
	then
		m.addResult("เพลี้ยกระโดดสีน้ำตาล","แมลง");
		m.addResult("เพลี้ยจักจั่นสีเขียว","แมลง");
end
rule "125"
	when
		m:Message(message=="กข6ต้านทาน");
	then
		m.addResult("ใบจุดสีน้ำตาล","โรค");
end
rule "126"
	when
		m:Message(message=="สันป่าตองต้านทาน");
	then
		m.addResult("ไหม้","โรค");
		m.addResult("ขอบใบแห้ง","โรค");
end
rule "127"
	when
		m:Message(message=="เหนียวสันป่าตองต้านทาน");
	then
		m.addResult("ไหม้","โรค");
		m.addResult("ใบจุดสีน้ำตาล","โรค");
end
rule "128"
	when
		m:Message(message=="มีแผลลามทั้งต้น" || message=="ที่เกิดจากแผลลามทั้งต้น" || message=="เกิดจากแผลลามทั้งต้น");
	then
		m.addResult("กล้าเน่าในกระบะเพาะ","โรค");
end
rule "129"
	when
		m:Message(message=="สุพรรณบุรี1ต้านทาน");
	then
		m.addResult("ใบหงิก","โรค");
		m.addResult("ไหม้","โรค");
		m.addResult("ขอบใบแห้ง","โรค");
		m.addResult("ใบสีส้ม","โรค");
end
rule "130"
	when
		m:Message(message=="มีแผลลามถึงใบ" || message=="เกิดจากแผลลามถึงใบ" || message=="ที่เกิดจากแผลลามถึงใบ");
	then
		m.addResult("กาบใบแห้ง","โรค");
end
rule "131"
	when
		m:Message(message=="มีจุดช้ำขยายตัว" || message=="เกิดจากจุดช้ำขยายตัว" || message=="ที่เกิดจากจุดช้ำขยายตัว");
	then
		m.addResult("ขอบใบแห้ง","โรค");
end
rule "132"
	when
		m:Message(message=="พิษณุโลก2ต้านทาน");
	then
		m.addResult("ไหม้","โรค");
		m.addResult("ขอบใบแห้ง","โรค");
end
rule "133"
	when
		m:Message(message=="ระยะกล้า");
	then
		m.addResult("ไหม้","โรค");
		m.addResult("ขอบใบแห้ง","โรค");
		m.addResult("รากปม","โรค");
		m.addResult("กล้าเน่าในกระบะเพาะ","โรค");
		m.addResult("ถอดฝักดาบ","โรค");
		m.addResult("ใบหงิก","โรค");
end
rule "134"
	when
		m:Message(message=="ระยะแตกกอ");
	then
		m.addResult("ไหม้","โรค");
		m.addResult("ขอบใบแห้ง","โรค");
		m.addResult("รากปม","โรค");
		m.addResult("ถอดฝักดาบ","โรค");
		m.addResult("กาบใบแห้ง","โรค");
		m.addResult("ใบขีดโปร่งแสง","โรค");
		m.addResult("ใบจุดสีน้ำตาล","โรค");
		m.addResult("ใบวงสีน้ำตาล","โรค");
		m.addResult("ใบสีส้ม","โรค");
		m.addResult("ใบหงิก","โรค");
end
rule "135"
	when
		m:Message(message=="ระยะออกรวง");
	then
		m.addResult("ไหม้","โรค");
		m.addResult("ขอบใบแห้ง","โรค");
		m.addResult("รากปม","โรค");
		m.addResult("ถอดฝักดาบ","โรค");
		m.addResult("กาบใบแห้ง","โรค");
		m.addResult("ใบขีดโปร่งแสง","โรค");
		m.addResult("ใบสีส้ม","โรค");
		m.addResult("ใบหงิก","โรค");
		m.addResult("เมล็ดด่าง","โรค");
end
rule "136"
	when
		m:Message(message=="กาบใบแห้ง");
	then
		m.addResult("เกิดในช่วงนาปี","ข้อมูลโรค");
		m.addResult("นาปรัง","ข้อมูลโรค");
		m.addResult("ระยะแตกกอ","ข้อมูลโรค");
		m.addResult("ระยะตั้งท้อง","ข้อมูลโรค");
		m.addResult("ออกรวง","ข้อมูลโรค");
		m.addResult("เกิดจากเชื้อรา","ข้อมูลโรค");
		m.addResult("ใบ กาบใบ รวง","ข้อมูลโรค");
		m.addResult("แผลสีเขียวปนเทา","ข้อมูลโรค");
		m.addResult("ไม่ทราบพาหะ","ข้อมูลโรค");
end
rule "137"
	when
		m:Message(message=="ปลูกภาคเหนือ" || message=="ปลูกที่ภาคเหนือ" || message=="ภาคเหนือ");
	then
		m.addResult("ขาวดอกมะลิ105","ข้าว");
		m.addResult("กข6","ข้าว");
		m.addResult("เหนียวสันป่าตอง","ข้าว");
		m.addResult("สันป่าตอง","ข้าว");
		m.addResult("ชัยนาท1","ข้าว");
		m.addResult("สุพรรณบุรี1","ข้าว");
		m.addResult("พิษณุโลก2","ข้าว");
		m.addResult("ปราจีนบุรี1","ข้าว");
end
rule "138"
	when
		m:Message(message=="ปลูกภาคเหนือตอนบน");
	then
		m.addResult("ขาวดอกมะลิ105","ข้าว");
		m.addResult("สันป่าตอง","ข้าว");
end
rule "139"
	when
		m:Message(message=="ปลูกภาคเหนือตอนล่าง");
	then
		m.addResult("ชัยนาท1","ข้าว");
		m.addResult("พิษณุโลก2","ข้าว");
		m.addResult("ปราจีนบุรี1","ข้าว");
end
rule "140"
	when
		m:Message(message=="นาปรัง" || message=="เขตชลประทาน");
	then
		m.addResult("สันป่าตอง","ข้าว");
		m.addResult("สุพรรณบุรี1","ข้าว");
		m.addResult("พิษณุโลก2","ข้าว");
end
rule "141"
	when
		m:Message(message=="นาปี");
	then
		m.addResult("ขาวดอกมะลิ105","ข้าว");
		m.addResult("กข6","ข้าว");
		m.addResult("เหนียวสันป่าตอง","ข้าว");
		m.addResult("ชัยนาท1","ข้าว");
		m.addResult("พิษณุโลก2","ข้าว");
		m.addResult("ปราจีนบุรี1","ข้าว");
end
rule "142"
	when
		m:Message(message=="ข้าวเจ้า");
	then
		m.addResult("ขาวดอกมะลิ105","ข้าว");
		m.addResult("ชัยนาท1","ข้าว");
		m.addResult("สุพรรณบุรี1","ข้าว");
		m.addResult("พิษณุโลก2","ข้าว");
		m.addResult("ปราจีนบุรี1","ข้าว");
end
rule "143"
	when
		m:Message(message=="ข้าวเหนียว");
	then
		m.addResult("กข6","ข้าว");
		m.addResult("เหนียวสันป่าตอง","ข้าว");
		m.addResult("สันป่าตอง","ข้าว");
end
rule "144"
	when
		m:Message(message=="ในภาคเหนือ" || message=="ที่พบในภาคเหนือ");
	then
		m.addResult("ไหม้","โรค");
		m.addResult("เมล็ดด่าง","โรค");
		m.addResult("ใบจุดสีน้ำตาล","โรค");
		m.addResult("ถอดฝักดาบ","โรค");
		m.addResult("ใบขีดสีน้ำตาล","โรค");
		m.addResult("ใบวงสีน้ำตาล","โรค");
		m.addResult("รากปม","โรค");
		m.addResult("กล้าเน่าในกระบะเพาะ","โรค");
		m.addResult("ลำต้นเน่า","โรค");
		m.addResult("ใบสีส้ม","โรค");
		m.addResult("กาบใบแห้ง","โรค");
		m.addResult("ขอบใบแห้ง","โรค");
end
rule "145"
	when
		m:Message(message=="เชื้อแบคทีเรีย" || message=="ที่เกิดจากเชื้อแบคทีเรีย");
	then
		m.addResult("ขอบใบแห้ง","โรค");
end
rule "146"
	when
		m:Message(message=="เชื้อไฟโตพลาสมา" || message=="ที่เกิดจากเชื้อไฟโตพลาสมา");
	then
		m.addResult("ขอบใบแห้ง","โรค");
end
rule "147"
	when
		m:Message(message=="ไส้เดือนฝอย" || message=="ที่เกิดจากไส้เดือนฝอย");
	then
		m.addResult("รากปม","โรค");
end
rule "148"
	when
		m:Message(message=="เกิดที่ใบ");
	then
		m.addResult("ไหม้","โรค");
		m.addResult("ใบจุดสีน้ำตาล","โรค");
		m.addResult("ขอบใบแห้ง","โรค");
		m.addResult("ใบสีส้ม","โรค");
		m.addResult("กาบใบแห้ง","โรค");
		m.addResult("ใบวงสีน้ำตาล","โรค");
		m.addResult("รากปม","โรค");
end
rule "149"
	when
		m:Message(message=="เกิดที่รวง");
	then
		m.addResult("ไหม้","โรค");
		m.addResult("เมล็ดด่าง","โรค");
		m.addResult("กาบใบแห้ง","โรค");
		m.addResult("ใบจุดสีน้ำตาล","โรค");
		m.addResult("ใบขีดสีน้ำตาล","โรค");
end
rule "150"
	when
		m:Message(message=="เชื้อแบคทีเรีย" || message=="ที่เกิดจากเชื้อแบคทีเรีย");
	then
		m.addResult("ขอบใบแห้ง","โรค");
end
rule "151"
	when
		m:Message(message=="โรคไหม้" || message=="ข้าวที่ต้านทานโรคไหม้");
	then
		m.addResult("ลูกแดงปัตตานี","ข้าว");
		m.addResult("กข13","ข้าว");
		m.addResult("กข37","ข้าว");
		m.addResult("กู้เมืองหลวง","ข้าว");
		m.addResult("ดอกพะยอม","ข้าว");
		m.addResult("กข43","ข้าว");
end
rule "152"
	when
		m:Message(message=="โรคใบจุดสีน้ำตาล" || message=="ข้าวที่ต้านทานโรคใบจุดสีน้ำตาล");
	then
		m.addResult("พวงไร่2","ข้าว");
		m.addResult("นางพญา132","ข้าว");
		m.addResult("เผือกน้ำ43","ข้าว");
		m.addResult("กข1","ข้าว");
		m.addResult("กู้เมืองหลวง","ข้าว");
		m.addResult("ดอกพะยอม","ข้าว");
end
rule "153"
	when
		m:Message(message=="โรคใบสีส้ม" || message=="ข้าวที่ต้านทานโรคใบสีส้ม");
	then
		m.addResult("นางพญา132","ข้าว");
end
rule "154"
	when
		m:Message(message=="โรคใบหงิก" || message=="ข้าวที่ต้านทานโรคใบหงิก");
	then
		m.addResult("แก่นจันทร์","ข้าว");
end
rule "155"
	when
		m:Message(message=="โรคใบขีดสีน้ำตาล" || message=="ข้าวที่ต้านทานโรคใบขีดสีน้ำตาล");
	then
		m.addResult("แก่นจันทร์","ข้าว");
		m.addResult("กู้เมืองหลวง","ข้าว");
		m.addResult("ดอกพะยอม","ข้าว");
		m.addResult("กข7","ข้าว");
end
rule "156"
	when
		m:Message(message=="โรคขอบใบแห้ง" || message=="ข้าวที่ต้านทานโรคขอบใบแห้ง");
	then
		m.addResult("กข37","ข้าว");
		m.addResult("เข็มทอง","ข้าว");
		m.addResult("กข7","ข้าว");
end
rule "157"
	when
		m:Message(message=="ไวต่อแสง" || message=="ที่ไวต่อแสง");
	then
		m.addResult("ลูกแดงปัตตานี","ข้าว");
		m.addResult("กข13","ข้าว");
		m.addResult("เล็บนกปัตตานี","ข้าว");
		m.addResult("พวงไร่ 2 เผือกน้ำ43","ข้าว");
		m.addResult("นางพญา132","ข้าว");
		m.addResult("แก่นจันทร์","ข้าว");
		m.addResult("กู้เมืองหลวง","ข้าว");
		m.addResult("สังข์หยดพัทลุง","ข้าว");
		m.addResult("ดอกพะยอม","ข้าว");
		m.addResult("เข็มทอง","ข้าว");
end
rule "158"
	when
		m:Message(message=="ไม่ไวต่อแสง" || message=="ที่ไม่ไวต่อแสง");
	then
		m.addResult("กข1","ข้าว");
		m.addResult("พัทลุง","ข้าว");
		m.addResult("กข37","ข้าว");
		m.addResult("กข7","ข้าว");
		m.addResult("กข43","ข้าว");
end
rule "159"
	when
		m:Message(message=="นาปี" || message=="ที่ปลูกแบบนาปี");
	then
		m.addResult("ลูกแดงปัตตานี","ข้าว");
		m.addResult("กข13","ข้าว");
		m.addResult("เล็บนกปัตตานี","ข้าว");
		m.addResult("พวงไร่2","ข้าว");
		m.addResult("เผือกน้ำ43","ข้าว");
		m.addResult("นางพญา132","ข้าว");
		m.addResult("แก่นจันทร์","ข้าว");
		m.addResult("กู้เมืองหลวง","ข้าว");
		m.addResult("สังข์หยดพัทลุง","ข้าว");
		m.addResult("ดอกพะยอม","ข้าว");
		m.addResult("เข็มทอง","ข้าว");
end
rule "160"
	when
		m:Message(message=="นาปรัง" || message=="ที่ปลูกแบบนาปรัง");
	then
		m.addResult("กข1","ข้าว");
		m.addResult("พัทลุง","ข้าว");
		m.addResult("กข37","ข้าว");
		m.addResult("กข7","ข้าว");
		m.addResult("กข43","ข้าว");
end
rule "161"
	when
		m:Message(message=="ชลประทาน" || message=="ที่ต้องการชลประทาน");
	then
		m.addResult("กข1","ข้าว");
		m.addResult("กข37","ข้าว");
		m.addResult("กข43","ข้าว");
end
rule "162"
	when
		m:Message(message=="ข้าวในภาคใต้อ่อนแอต่อ");
	then
		m.addResult("ไหม้","โรค");
		m.addResult("กาบใบแห้ง","โรค");
		m.addResult("เมล็ดด่าง","โรค");
		m.addResult("ขอบใบแห้ง","โรค");
		m.addResult("ใบวงสีน้ำตาล","โรค");
		m.addResult("ใบจุดสีน้ำตาล","โรค");
		m.addResult("ใบขีดโปร่งแสง","โรค");
		m.addResult("ใบขีดสีน้ำตาล","โรค");
		m.addResult("ลำต้นเน่า","โรค");
end
rule "163"
	when
		m:Message(message=="ลูกแดงปัตตานีอ่อนแอต่อ");
	then
		m.addResult("ขอบใบแห้ง","โรค");
end
rule "164"
	when
		m:Message(message=="กข13อ่อนแอต่อ");
	then
		m.addResult("ขอบใบแห้ง","โรค");
end
rule "165"
	when
		m:Message(message=="เล็บนกปัตตานีอ่อนแอต่อ");
	then
		m.addResult("ไหม้","โรค");
end
rule "166"
	when
		m:Message(message=="เผือกน้ำ43อ่อนแอต่อ");
	then
		m.addResult("ไหม้","โรค");
		m.addResult("โรคใบสีส้ม","โรค");
end
rule "167"
	when
		m:Message(message=="นางพญา132อ่อนแอต่อ");
	then
		m.addResult("ไหม้","โรค");
		m.addResult("ใบหงิก","โรค");
end
rule "168"
	when
		m:Message(message=="กข1อ่อนแอต่อ");
	then
		m.addResult("ขอบใบแห้ง","โรค");
		m.addResult("ใบหงิก","โรค");
		m.addResult("ใบขีดสีน้ำตาล","โรค");
end
rule "169"
	when
		m:Message(message=="แก่นจันทร์อ่อนแอต่อ");
	then
		m.addResult("ไหม้","โรค");
end
rule "170"
	when
		m:Message(message=="กู้เมืองหลวงอ่อนแอต่อ");
	then
		m.addResult("ขอบใบแห้ง","โรค");
		m.addResult("ใบวงสีน้ำตาล","โรค");
end
rule "171"
	when
		m:Message(message=="สังข์หยดพัทลุงอ่อนแอต่อ");
	then
		m.addResult("ไหม้","โรค");
end
rule "172"
	when
		m:Message(message=="ดอกพระยอมอ่อนแอต่อ");
	then
		m.addResult("ขอบใบแห้ง","โรค");
		m.addResult("ใบวงสีน้ำตาล","โรค");
end
rule "173"
	when
		m:Message(message=="เข็มทอง");
	then
		m.addResult("ไหม้","โรค");
end
rule "174"
	when
		m:Message(message=="กข7 อ่อนแอต่อ");
	then
		m.addResult("ไหม้","โรค");
		m.addResult("ใบหงิก","โรค");
end
rule "175"
	when
		m:Message(message=="ลำต้นส่วนสูงผิดปรกติ");
	then
		m.addResult("ถอดฝักดาบ","โรค");
		m.addResult("ใบสีส้ม","โรค");
		m.addResult("ใบหงิก","โรค");
		m.addResult("เมาตอซัง","โรค");
end
rule "176"
	when
		m:Message(message=="ลำต้นสีเขียวอ่อนซีด");
	then
		m.addResult("ถอดฝักดาบ","โรค");
end
rule "177"
	when
		m:Message(message=="รากแผลสีน้ำตาล");
	then
		m.addResult("กล้าเน่าในกระบะเพาะ","โรค");
end
rule "178"
	when
		m:Message(message=="รากเน่าดำ");
	then
		m.addResult("เมาตอซัง","โรค");
end
rule "179"
	when
		m:Message(message=="ใบแคบและสั้น");
	then
		m.addResult("ใบหงิก","โรค");
end
rule "180"
	when
		m:Message(message=="ใบสีเขียวเข้ม");
	then
		m.addResult("ใบหงิก","โรค");
end
rule "181"
	when
		m:Message(message=="ใบแผลสีเขียวเทา");
	then
		m.addResult("กาบใบแห้ง","โรค");
		m.addResult("ถอดฝักดาบ","โรค");
end
rule "182"
	when
		m:Message(message=="ใบแห้ง");
	then
		m.addResult("กาบใบแห้ง","โรค");
		m.addResult("ขอบใบแห้ง","โรค");
end
rule "183"
	when
		m:Message(message=="ใบแผลสีเหลือง");
	then
		m.addResult("ขอบใบแห้ง","โรค");
		m.addResult("เมาตอซัง","โรค");
end
rule "184"
	when
		m:Message(message=="ใบสีส้ม");
	then
		m.addResult("ใบสีส้ม","โรค");
end
rule "185"
	when
		m:Message(message=="ใบสีน้ำตาล");
	then
		m.addResult("ขอบใบแห้ง","โรค");
end
rule "186"
	when
		m:Message(message=="ใบจุดสีน้ำตาล");
	then
		m.addResult("ใบจุดสีน้ำตาล","โรค");
		m.addResult("ใบสีส้ม","โรค");
end
rule "187"
	when
		m:Message(message=="ใบช้ำ");
	then
		m.addResult("ใบขีดโปร่งแสง","โรค");
end
rule "188"
	when
		m:Message(message=="เมล็ดข้าวไม่งอก");
	then
		m.addResult("กล้าเน่าในกระบะเพาะ","โรค");
end
rule "189"
	when
		m:Message(message=="แผลจุดสีน้ำตาล");
	then
		m.addResult("เมล็ดด่าง","โรค");
end
rule "190"
	when
		m:Message(message=="รวงข้าวไม่สมบูรณ์");
	then
		m.addResult("ใบหงิก","โรค");
end
rule "191"
	when
		m:Message(message=="แผลลามทั้งต้น");
	then
		m.addResult("กล้าเน่าในกระบะเพาะ","โรค");
end
rule "192"
	when
		m:Message(message=="แผลลามถึงใบ");
	then
		m.addResult("กาบใบแห้ง","โรค");
end
rule "193"
	when
		m:Message(message=="จุดช้ำขยายตัว");
	then
		m.addResult("ขอบใบแห้ง","โรค");
end
rule "194"
	when
		m:Message(message=="ระยะกล้า" || message=="ที่เกิดในระยะกล้า");
	then
		m.addResult("กล้าเน่าในกระบะเพาะ","โรค");
		m.addResult("ถอดฝักดาบ","โรค");
		m.addResult("ใบสีส้ม","โรค");
		m.addResult("ใบหงิก","โรค");
end
rule "195"
	when
		m:Message(message=="ระยะแตกกอ" || message=="ที่เกิดในระยะแตกกอ");
	then
		m.addResult("กาบใบแห้ง","โรค");
		m.addResult("ใบขีดโปร่งแสง","โรค");
		m.addResult("ใบจุดสีน้ำตาล","โรค");
		m.addResult("ใบสีส้ม","โรค");
		m.addResult("ใบหงิก","โรค");
		m.addResult("เมาตอซัง","โรค");
end
rule "196"
	when
		m:Message(message=="ระยะออกรวง");
	then
		m.addResult("กาบใบแห้ง","โรค");
		m.addResult("ใบขีดโปร่งแสง","โรค");
		m.addResult("ใบสีส้ม","โรค");
		m.addResult("ใบหงิก","โรค");
		m.addResult("เมล็ดด่าง","โรค");
end
rule "197"
	when
		m:Message(message=="ภาคใต้");
	then
		m.addResult("ลูกแดงปัตตานี","ข้าว");
		m.addResult("กข13","ข้าว");
		m.addResult("เล็บนกปัตตานี","ข้าว");
		m.addResult("พวงไร่2","ข้าว");
		m.addResult("เผือกน้ำ43","ข้าว");
		m.addResult("นางพญา132","ข้าว");
		m.addResult("กข1","ข้าว");
		m.addResult("แก่นจันทร์","ข้าว");
		m.addResult("พัทลุง","ข้าว");
		m.addResult("กข37","ข้าว");
		m.addResult("กู้เมืองหลวง","ข้าว");
		m.addResult("สังข์หยดพัทลุง","ข้าว");
		m.addResult("ดอกพะยอม","ข้าว");
		m.addResult("เข็มทอง","ข้าว");
		m.addResult("กข7","ข้าว");
		m.addResult("กข43","ข้าว");
end
rule "198"
	when
		m:Message(message=="รากเน่าใบกระบะเพาะ");
	then
		m.addResult("เกิดในช่วงนาปรัง","ข้อมูลโรค");
		m.addResult("ระยะหลังจากการตกกล้าข้าว","ข้อมูลโรค");
		m.addResult("เกิดจากเชื้อรา","ข้อมูลโรค");
		m.addResult("เมล็ด ราก โคนต้นมีแผลสีน้ำตาล","ข้อมูลโรค");
		m.addResult("ลุกลาม","ข้อมูลโรค");
end
rule "199"
	when
		m:Message(message=="กาบใบแห้ง");
	then
		m.addResult("เกิดในช่วงนาปี","ข้อมูลโรค");
		m.addResult("นาปรัง","ข้อมูลโรค");
		m.addResult("ระยะแตกกอ","ข้อมูลโรค");
		m.addResult("ระยะตั้งท้อง","ข้อมูลโรค");
		m.addResult("ออกรวง","ข้อมูลโรค");
		m.addResult("เกิดจากเชื้อรา","ข้อมูลโรค");
		m.addResult("ใบ กาบใบ รวง","ข้อมูลโรค");
		m.addResult("แผลสีเขียวปนเทา","ข้อมูลโรค");
		m.addResult("ใบพาหะ","ข้อมูลโรค");
end
rule "200"
	when
		m:Message(message=="รากปม");
	then
		m.addResult("เกิดในช่วงนาปี","ข้อมูลโรค");
		m.addResult("ระยะกล้า","ข้อมูลโรค");
		m.addResult("ระยะแตกกอ","ข้อมูลโรค");
		m.addResult("ระยะตั้งท้อง","ข้อมูลโรค");
		m.addResult("ออกรวง","ข้อมูลโรค");
		m.addResult("เกิดจากไส้เดือนฝอย","ข้อมูลโรค");
		m.addResult("รากพอง","ข้อมูลโรค");
		m.addResult("ใบสีเหลือง","ข้อมูลโรค");
		m.addResult("ต้นแคระเกร็น","ข้อมูลโรค");
		m.addResult("ไม่ทราบพาหะ","ข้อมูลโรค");
end
rule "201"
	when
		m:Message(message=="ไหม้");
	then
		m.addResult("เกิดในช่วงนาปี","ข้อมูลโรค");
		m.addResult("ระยะกล้า","ข้อมูลโรค");
		m.addResult("ระยะแตกกอ","ข้อมูลโรค");
		m.addResult("ระยะตั้งท้อง","ข้อมูลโรค");
		m.addResult("ออกรวง","ข้อมูลโรค");
		m.addResult("คอรวง","ข้อมูลโรค");
		m.addResult("เกิดจากเชื้อรา","ข้อมูลโรค");
		m.addResult("ข้อลำต้น ข้อต่อใบ มีแผล","ข้อมูลโรค");
		m.addResult("ใบรวง","ข้อมูลโรค");
		m.addResult("แผลสีน้ำตาล","ข้อมูลโรค");
		m.addResult("จุดรูปตา","ข้อมูลโรค");
		m.addResult("ไม่ทราบพาหะ","ข้อมูลโรค");
end
rule "202"
	when
		m:Message(message=="ขอบใบแห้ง");
	then
		m.addResult("เกิดในช่วงนาปี","ข้อมูลโรค");
		m.addResult("ระยะกล้า","ข้อมูลโรค");
		m.addResult("ระยะแตกกอ","ข้อมูลโรค");
		m.addResult("ระยะตั้งท้อง","ข้อมูลโรค");
		m.addResult("ออกรวง","ข้อมูลโรค");
		m.addResult("เกิดจากเชื้อแบคทีเรีย","ข้อมูลโรค");
		m.addResult("ใบช้ำสีน้ำตาล","ข้อมูลโรค");
		m.addResult("ขีดสีเหลือง","ข้อมูลโรค");
		m.addResult("ไม่ทราบพาหะ","ข้อมูลโรค");
end
rule "203"
	when
		m:Message(message=="กาบใบแห้ง");
	then
		m.addResult("เกิดในช่วงนาปี","ข้อมูลโรค");
		m.addResult("นาปรัง","ข้อมูลโรค");
		m.addResult("ระยะแตกกอ","ข้อมูลโรค");
		m.addResult("ระยะตั้งท้อง","ข้อมูลโรค");
		m.addResult("ออกรวง","ข้อมูลโรค");
		m.addResult("เกิดจากเชื้อรา","ข้อมูลโรค");
		m.addResult("ใบ กาบใบ รวง","ข้อมูลโรค");
		m.addResult("แผลสีเขียวปนเทา","ข้อมูลโรค");
		m.addResult("ไม่ทราบพาหะ","ข้อมูลโรค");
end
rule "204"
	when
		m:Message(message=="ถอดฝักดาบ");
	then
		m.addResult("เกิดในช่วงนาปี","ข้อมูลโรค");
		m.addResult("นาปรัง","ข้อมูลโรค");
		m.addResult("ระยะกล้า","ข้อมูลโรค");
		m.addResult("ระยะแตกกอ","ข้อมูลโรค");
		m.addResult("ระยะตั้งท้อง","ข้อมูลโรค");
		m.addResult("ออกรวง","ข้อมูลโรค");
		m.addResult("เกิดจากเชื้อรา","ข้อมูลโรค");
		m.addResult("ต้น ย่างปล้อง","ข้อมูลโรค");
		m.addResult("รากเน่าช้า สีเขียวซีด ลุกลาม","ข้อมูลโรค");
		m.addResult("ไม่ทราบพาหะ","ข้อมูลโรค");
end
rule "205"
	when
		m:Message(message=="เมล็ดด่าง");
	then
		m.addResult("เกิดในช่วงนาปี","ข้อมูลโรค");
		m.addResult("นาปรัง","ข้อมูลโรค");
		m.addResult("ระยะออกรวง","ข้อมูลโรค");
		m.addResult("เกิดจากเชื้อรา","ข้อมูลโรค");
		m.addResult("เมล็ดเป็นแผล จุดสีน้ำตาลหรือสีดำ","ข้อมูลโรค");
		m.addResult("ลายสีน้ำตาลดำหรือเทาปนชมพู","ข้อมูลโรค");
end
rule "206"
	when
		m:Message(message=="ใบจุดสีน้ำตาล");
	then
		m.addResult("เกิดในช่วงนาปี","ข้อมูลโรค");
		m.addResult("ระยะแตกกอ","ข้อมูลโรค");
		m.addResult("เกิดจากเชื้อรา","ข้อมูลโรค");
		m.addResult("ต้น คอรวง ข้อลำต้น ข้อต่อใบ ใบ มีแผลสีน้ำตาล","ข้อมูลโรค");
		m.addResult("จุดรูปไข่","ข้อมูลโรค");
		m.addResult("จุดกลม","ข้อมูลโรค");
		m.addResult("สีสนิม","ข้อมูลโรค");
		m.addResult("รอย","ข้อมูลโรค");
		m.addResult("ลุกลาม","ข้อมูลโรค");
end
rule "207"
	when
		m:Message(message=="ใบวงสีน้ำตาล");
	then
		m.addResult("เกิดในช่วงนาปรัง","ข้อมูลโรค");
		m.addResult("ระยะแตกกอ","ข้อมูลโรค");
		m.addResult("ไม่ทราบพาหะ","ข้อมูลโรค");
		m.addResult("ปลายใบ","ข้อมูลโรค");
		m.addResult("ใบมีแผลช้ำ สีน้ำตาล รูปไข่","ข้อมูลโรค");
end
rule "208"
	when
		m:Message(message=="ระยะตั้งท้อง" || message=="เกิดในระยะตั้งท้อง");
	then
		m.addResult("ไหม้","โรค");
		m.addResult("ขอบใบแห้ง","โรค");
		m.addResult("รากปม","โรค");
		m.addResult("ถอดฝักดาบ","โรค");
		m.addResult("กาบใบแห้ง","โรค");
end
rule "209"
	when
		m:Message(message=="ระยะออกรวง" || message=="เกิดในระยะออกรวง");
	then
		m.addResult("ไหม้","โรค");
		m.addResult("ขีดสีน้ำตาล","โรค");
		m.addResult("ใบจุดสีน้ำตาล","โรค");
end
rule "210"
	when
		m:Message(message=="เกิดที่ราก");
	then
		m.addResult("รากปม","โรค");
end
rule "211"
	when
		m:Message(message=="เกิดที่ต้น");
	then
		m.addResult("ถอดฝักดาบ","โรค");
		m.addResult("กาบใบแห้ง","โรค");
		m.addResult("รากปม","โรค");
end
rule "212"
	when
		m:Message(message=="เกิดที่ข้อลำต้น");
	then
		m.addResult("ไหม้","โรค");
		m.addResult("ใบจุดสีน้ำตาล","โรค");
end
rule "213"
	when
		m:Message(message=="เกิดที่กาบใบ");
	then
		m.addResult("กาบใบแห้ง","โรค");
end
rule "214"
	when
		m:Message(message=="เกิดที่ข้อต่อใบ");
	then
		m.addResult("ไหม้","โรค");
		m.addResult("ใบจุดสีน้ำตาล","โรค");
end
rule "215"
	when
		m:Message(message=="เกิดที่รวง");
	then
		m.addResult("ไหม","โรค");
		m.addResult("เมล็ดด่าง","โรค");
		m.addResult("กาบใบแห้ง","โรค");
		m.addResult("ใบจุดสีน้ำตาล","โรค");
		m.addResult("ใบขีดสีน้ำตาล","โรค");
end
rule "216"
	when
		m:Message(message=="เกิดที่เมล็ด");
	then
		m.addResult("เมล็ดด่าง","โรค");
end
rule "217"
	when
		m:Message(message=="กข6ไม่ต้านทาน" || message=="กข6อ่อนแอต่อ");
	then
		m.addResult("ขอบใบแห้ง","โรค");
		m.addResult("ไหม้","โรค");
end
rule "218"
	when
		m:Message(message=="เหนียวสันป่าตองไม่ต้านทาน" || message=="เหนียวสันป่าตองอ่อนแอต่อ");
	then
		m.addResult("ใบสีส้ม","โรค");
		m.addResult("ขอบใบแห้ง","โรค");
end
rule "219"
	when
		m:Message(message=="ภาคใต้" || message=="ปลูกที่ภาคใต้");
	then
		m.addResult("ลูกแดงปัตตานี","ข้าว");
		m.addResult("กข13","ข้าว");
		m.addResult("เล็บนกปัตตานี","ข้าว");
		m.addResult("พวงไร่2","ข้าว");
		m.addResult("เผือกน้ำ43","ข้าว");
		m.addResult("นางพญา132","ข้าว");
		m.addResult("กข1","ข้าว");
		m.addResult("แก่นจันทร์","ข้าว");
		m.addResult("พัทลุง","ข้าว");
		m.addResult("กข37","ข้าว");
		m.addResult("กู้เมืองหลวง","ข้าว");
		m.addResult("สังข์หยดพัทลุง","ข้าว");
		m.addResult("ดอกพะยอม","ข้าว");
		m.addResult("เข็มทอง","ข้าว");
		m.addResult("กข7","ข้าว");
		m.addResult("กข4","ข้าว");
end
rule "220"
	when
		m:Message(message=="ภาคกลาง" || message=="ในภาคกลาง" || message=="ที่อยู่ในภาคกลาง");
	then
		m.addResult("กรุงเทพ","จังหวัด");
		m.addResult("สมุทรปราการ","จังหวัด");
		m.addResult("นนทบุรี","จังหวัด");
		m.addResult("นครสวรรค์","จังหวัด");
		m.addResult("ปทุมธานี","จังหวัด");
		m.addResult("เพชรบูรณ์","จังหวัด");
		m.addResult("นครปฐม","จังหวัด");
		m.addResult("พิษณุโลก","จังหวัด");
		m.addResult("สุพรรณบุรี","จังหวัด");
		m.addResult("พระนครศรีอยุธยา","จังหวัด");
		m.addResult("อยุธยา","จังหวัด");
		m.addResult("ลพบุรี","จังหวัด");
		m.addResult("กำแพงเพชร","จังหวัด");
		m.addResult("สระบุรี","จังหวัด");
		m.addResult("สุโขทัย","จังหวัด");
		m.addResult("พิจิตร","จังหวัด");
		m.addResult("สมุทรสาคร","จังหวัด");
		m.addResult("ชัยนาท","จังหวัด");
		m.addResult("อุทัยธานี","จังหวัด");
		m.addResult("อ่างทอง","จังหวัด");
		m.addResult("นครนายก","จังหวัด");
		m.addResult("สิงห์บุรี","จังหวัด");
		m.addResult("สมุทรสงคราม","จังหวัด");
end
